# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("font: 12pt \"Noto Sans\";\n"
"background-color: #E0F2E9;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(220, 0))
        self.frame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame.setStyleSheet("background-color: #fff;\n"
"border-radius: 5px")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 180))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setText("")
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.scrollArea.setStyleSheet("*{\n"
";\n"
"    font: 87 10pt \"Noto Sans Black\";\n"
"color: #1E1E1E;\n"
"}\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F0F0F0;\n"
"                width: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 202, 378))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(185, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(185, 16777215))
        self.frame_2.setStyleSheet("#frame_2 QFrame:hover{\n"
"background-color: #A8D5BA;\n"
"}\n"
"QPushButton, QLabel, QFrame{\n"
"background-color: transparent;\n"
"}\n"
"QPushButton{\n"
"text-align: left;\n"
"}\n"
"QPushButton:pressed ~ QFrame{\n"
"background-color: #228B22;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_15.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.dashboard_logo = QtWidgets.QLabel(parent=self.frame_17)
        self.dashboard_logo.setMinimumSize(QtCore.QSize(20, 20))
        self.dashboard_logo.setMaximumSize(QtCore.QSize(20, 20))
        self.dashboard_logo.setStyleSheet("image url(:/icons/dashboard.png)")
        self.dashboard_logo.setText("")
        self.dashboard_logo.setPixmap(QtGui.QPixmap(".\\../../../resources/icons/dashboard.png"))
        self.dashboard_logo.setScaledContents(True)
        self.dashboard_logo.setObjectName("dashboard_logo")
        self.horizontalLayout_15.addWidget(self.dashboard_logo)
        self.horizontalLayout_2.addWidget(self.frame_17)
        self.dashboard_pushButton = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dashboard_pushButton.sizePolicy().hasHeightForWidth())
        self.dashboard_pushButton.setSizePolicy(sizePolicy)
        self.dashboard_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.dashboard_pushButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.dashboard_pushButton.setFlat(False)
        self.dashboard_pushButton.setObjectName("dashboard_pushButton")
        self.horizontalLayout_2.addWidget(self.dashboard_pushButton)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.orders_logo = QtWidgets.QLabel(parent=self.frame_20)
        self.orders_logo.setMinimumSize(QtCore.QSize(20, 20))
        self.orders_logo.setMaximumSize(QtCore.QSize(20, 20))
        self.orders_logo.setText("")
        self.orders_logo.setPixmap(QtGui.QPixmap(".\\../../../resources/icons/booking.png"))
        self.orders_logo.setScaledContents(True)
        self.orders_logo.setObjectName("orders_logo")
        self.horizontalLayout_18.addWidget(self.orders_logo)
        self.horizontalLayout_5.addWidget(self.frame_20, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.orders_pushButton = QtWidgets.QPushButton(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orders_pushButton.sizePolicy().hasHeightForWidth())
        self.orders_pushButton.setSizePolicy(sizePolicy)
        self.orders_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.orders_pushButton.setObjectName("orders_pushButton")
        self.horizontalLayout_5.addWidget(self.orders_pushButton)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_16)
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.logout_logo = QtWidgets.QLabel(parent=self.frame_29)
        self.logout_logo.setMinimumSize(QtCore.QSize(20, 20))
        self.logout_logo.setMaximumSize(QtCore.QSize(20, 20))
        self.logout_logo.setText("")
        self.logout_logo.setPixmap(QtGui.QPixmap(".\\../../../resources/icons/logout.png"))
        self.logout_logo.setScaledContents(True)
        self.logout_logo.setObjectName("logout_logo")
        self.horizontalLayout_27.addWidget(self.logout_logo)
        self.horizontalLayout_14.addWidget(self.frame_29, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.logout_pushButton = QtWidgets.QPushButton(parent=self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_pushButton.sizePolicy().hasHeightForWidth())
        self.logout_pushButton.setSizePolicy(sizePolicy)
        self.logout_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logout_pushButton.setObjectName("logout_pushButton")
        self.horizontalLayout_14.addWidget(self.logout_pushButton)
        self.verticalLayout_4.addWidget(self.frame_16)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.scrollArea.raise_()
        self.frame_3.raise_()
        self.horizontalLayout.addWidget(self.frame)
        self.frame_30 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_30.setStyleSheet("")
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_32 = QtWidgets.QFrame(parent=self.frame_30)
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_32.setStyleSheet("background-color: #fff;\n"
"border-radius: 5px")
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_29.setContentsMargins(9, 5, 9, 5)
        self.horizontalLayout_29.setSpacing(5)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_33 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_33.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.current_page_label = QtWidgets.QLabel(parent=self.frame_33)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.current_page_label.setFont(font)
        self.current_page_label.setStyleSheet("font: 87 14pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.current_page_label.setText("")
        self.current_page_label.setObjectName("current_page_label")
        self.horizontalLayout_30.addWidget(self.current_page_label)
        self.horizontalLayout_29.addWidget(self.frame_33)
        self.frame_31 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(5)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.username_label = QtWidgets.QLabel(parent=self.frame_31)
        font = QtGui.QFont()
        font.setFamily("Noto Sans SemiBold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.username_label.setFont(font)
        self.username_label.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.username_label.setObjectName("username_label")
        self.horizontalLayout_28.addWidget(self.username_label)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem)
        self.profile_pushButton = QtWidgets.QPushButton(parent=self.frame_31)
        self.profile_pushButton.setMinimumSize(QtCore.QSize(25, 25))
        self.profile_pushButton.setMaximumSize(QtCore.QSize(25, 25))
        self.profile_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.profile_pushButton.setStyleSheet("background-color: #fff;\n"
"border: none;\n"
"color: black;\n"
"border-radius: 17px;")
        self.profile_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../../resources/icons/black-theme/user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.profile_pushButton.setIcon(icon)
        self.profile_pushButton.setObjectName("profile_pushButton")
        self.horizontalLayout_28.addWidget(self.profile_pushButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_29.addWidget(self.frame_31, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_5.addWidget(self.frame_32)
        self.content_widget = QtWidgets.QWidget(parent=self.frame_30)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.content_widget.sizePolicy().hasHeightForWidth())
        self.content_widget.setSizePolicy(sizePolicy)
        self.content_widget.setObjectName("content_widget")
        self.frame_34 = QtWidgets.QFrame(parent=self.content_widget)
        self.frame_34.setGeometry(QtCore.QRect(50, -110, 554, 45))
        self.frame_34.setStyleSheet("background-color: #fff;\n"
"border-radius: 5px")
        self.frame_34.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setSpacing(5)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.frame_35 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_35.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.current_page_label_2 = QtWidgets.QLabel(parent=self.frame_35)
        self.current_page_label_2.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.current_page_label_2.setObjectName("current_page_label_2")
        self.horizontalLayout_32.addWidget(self.current_page_label_2)
        self.horizontalLayout_31.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_36.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_33.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_33.setSpacing(5)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.profile_pushButton_2 = QtWidgets.QPushButton(parent=self.frame_36)
        self.profile_pushButton_2.setMinimumSize(QtCore.QSize(35, 35))
        self.profile_pushButton_2.setMaximumSize(QtCore.QSize(35, 35))
        self.profile_pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.profile_pushButton_2.setStyleSheet("background-color: #fff;\n"
"border: none;\n"
"color: black;\n"
"border-radius: 17px;")
        self.profile_pushButton_2.setText("")
        self.profile_pushButton_2.setIcon(icon)
        self.profile_pushButton_2.setObjectName("profile_pushButton_2")
        self.horizontalLayout_33.addWidget(self.profile_pushButton_2, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_31.addWidget(self.frame_36, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_5.addWidget(self.content_widget)
        self.horizontalLayout.addWidget(self.frame_30)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Magtibay LPG Trading Inventory System"))
        self.dashboard_pushButton.setText(_translate("MainWindow", "Dashboard"))
        self.orders_pushButton.setText(_translate("MainWindow", "Orders"))
        self.logout_pushButton.setText(_translate("MainWindow", "Logout"))
        self.username_label.setText(_translate("MainWindow", "Profile"))
        self.current_page_label_2.setText(_translate("MainWindow", "n/a"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
