# Form implementation generated from reading ui file '.\update_profile.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(325, 430)
        Form.setMinimumSize(QtCore.QSize(325, 430))
        Form.setMaximumSize(QtCore.QSize(325, 430))
        Form.setStyleSheet("*{\n"
"font: 10pt \"Noto Sans\";\n"
"color: #1E1E1E;\n"
"border: none;\n"
"background-color: transparent;\n"
"}\n"
"#Form{\n"
"background-color: #E0F2E9;\n"
"}\n"
"QLineEdit, QPlainTextEdit{\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"background-color: #fff;\n"
"}\n"
"QComboBox{\n"
"font: 10pt \"Inter\";\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px\n"
"}\n"
"QComboBox::drop-down{\n"
"border: none;\n"
"background: transparent;\n"
"}\n"
"QComboBox::down-arrow {\n"
"image: none;               \n"
"border: none;              \n"
"width: 0; height: 0;       \n"
"border-left: 5px solid none; \n"
"border-right: 5px solid none;\n"
"border-top: 7px solid #228B22; \n"
"margin: 0;\n"
"}\n"
"QSpinBox{\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"background-color: transparent;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setStyleSheet("background-color: #fff;\n"
"border-radius: 5px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.fname_lineEdit = QtWidgets.QLineEdit(parent=self.frame_3)
        self.fname_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.fname_lineEdit.setMaximumSize(QtCore.QSize(200, 30))
        self.fname_lineEdit.setObjectName("fname_lineEdit")
        self.horizontalLayout_2.addWidget(self.fname_lineEdit)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_4.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lname_lineEdit = QtWidgets.QLineEdit(parent=self.frame_4)
        self.lname_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.lname_lineEdit.setMaximumSize(QtCore.QSize(200, 30))
        self.lname_lineEdit.setObjectName("lname_lineEdit")
        self.horizontalLayout_3.addWidget(self.lname_lineEdit)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_12.setMinimumSize(QtCore.QSize(80, 0))
        self.label_12.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_12.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.address_plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame_8)
        self.address_plainTextEdit.setMinimumSize(QtCore.QSize(200, 73))
        self.address_plainTextEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.address_plainTextEdit.setObjectName("address_plainTextEdit")
        self.horizontalLayout_7.addWidget(self.address_plainTextEdit, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_2.addWidget(self.frame_8)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_6.setMinimumSize(QtCore.QSize(80, 0))
        self.label_6.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_6.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.username_lineEdit = QtWidgets.QLineEdit(parent=self.frame_5)
        self.username_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.username_lineEdit.setMaximumSize(QtCore.QSize(200, 30))
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.horizontalLayout_4.addWidget(self.username_lineEdit)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_8.setMinimumSize(QtCore.QSize(80, 0))
        self.label_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_8.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.email_lineEdit = QtWidgets.QLineEdit(parent=self.frame_6)
        self.email_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.email_lineEdit.setMaximumSize(QtCore.QSize(200, 30))
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.horizontalLayout_5.addWidget(self.email_lineEdit)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_14.setMinimumSize(QtCore.QSize(80, 0))
        self.label_14.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_14.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.role_comboBox = QtWidgets.QComboBox(parent=self.frame_9)
        self.role_comboBox.setMinimumSize(QtCore.QSize(200, 30))
        self.role_comboBox.setMaximumSize(QtCore.QSize(200, 30))
        self.role_comboBox.setObjectName("role_comboBox")
        self.horizontalLayout_8.addWidget(self.role_comboBox)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_10.setMinimumSize(QtCore.QSize(80, 0))
        self.label_10.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_10.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.job_comboBox = QtWidgets.QComboBox(parent=self.frame_7)
        self.job_comboBox.setMinimumSize(QtCore.QSize(200, 30))
        self.job_comboBox.setMaximumSize(QtCore.QSize(200, 30))
        self.job_comboBox.setObjectName("job_comboBox")
        self.horizontalLayout_6.addWidget(self.job_comboBox)
        self.verticalLayout_2.addWidget(self.frame_7)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.update_pushButton = QtWidgets.QPushButton(parent=self.frame_10)
        self.update_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.update_pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.update_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.update_pushButton.setStyleSheet("background-color: #228B22;\n"
"font: 87 12pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"border-radius: 5px;")
        self.update_pushButton.setObjectName("update_pushButton")
        self.horizontalLayout_9.addWidget(self.update_pushButton)
        self.cancel_pushButton = QtWidgets.QPushButton(parent=self.frame_10)
        self.cancel_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.cancel_pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cancel_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_pushButton.setStyleSheet("background-color: #DC3545;\n"
"font: 87 12pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"border-radius: 5px;")
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.horizontalLayout_9.addWidget(self.cancel_pushButton)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Update Profile:"))
        self.label_2.setText(_translate("Form", "First Name:"))
        self.label_4.setText(_translate("Form", "Last Name:"))
        self.label_12.setText(_translate("Form", "Address:"))
        self.label_6.setText(_translate("Form", "Username:"))
        self.label_8.setText(_translate("Form", "Email:"))
        self.label_14.setText(_translate("Form", "Role:"))
        self.label_10.setText(_translate("Form", "Job:"))
        self.update_pushButton.setText(_translate("Form", "Update"))
        self.cancel_pushButton.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
