# Form implementation generated from reading ui file 'update_password.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(365, 200)
        Form.setMinimumSize(QtCore.QSize(365, 200))
        Form.setMaximumSize(QtCore.QSize(365, 200))
        Form.setStyleSheet("*{\n"
"font: 10pt \"Noto Sans\";\n"
"color: #1E1E1E;\n"
"background-color: transparent;\n"
"border: none;\n"
"}\n"
"#Form{\n"
"background-color: #E0F2E9;\n"
"}\n"
"QLineEdit, QPlainTextEdit{\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"background-color: #fff;\n"
"}\n"
"QComboBox{\n"
"font: 10pt \"Inter\";\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px\n"
"}\n"
"QComboBox::drop-down{\n"
"border: none;\n"
"background: transparent;\n"
"}\n"
"QComboBox::down-arrow {\n"
"image: none;               \n"
"border: none;              \n"
"width: 0; height: 0;       \n"
"border-left: 5px solid none; \n"
"border-right: 5px solid none;\n"
"border-top: 7px solid #228B22; \n"
"margin: 0;\n"
"}\n"
"QSpinBox{\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"background-color: transparent;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_3 = QtWidgets.QFrame(parent=Form)
        self.frame_3.setStyleSheet("background-color: #fff;\n"
"border-radius: 5px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_3.setMinimumSize(QtCore.QSize(125, 0))
        self.label_3.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_3.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.current_pass_lineEdit = QtWidgets.QLineEdit(parent=self.frame_5)
        self.current_pass_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.current_pass_lineEdit.setMaximumSize(QtCore.QSize(200, 30))
        self.current_pass_lineEdit.setObjectName("current_pass_lineEdit")
        self.horizontalLayout_4.addWidget(self.current_pass_lineEdit)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setMinimumSize(QtCore.QSize(125, 0))
        self.label_2.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_2.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.new_pass_lineEdit = QtWidgets.QLineEdit(parent=self.frame_2)
        self.new_pass_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.new_pass_lineEdit.setMaximumSize(QtCore.QSize(200, 30))
        self.new_pass_lineEdit.setObjectName("new_pass_lineEdit")
        self.horizontalLayout_2.addWidget(self.new_pass_lineEdit)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.update_pushButton = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_pushButton.sizePolicy().hasHeightForWidth())
        self.update_pushButton.setSizePolicy(sizePolicy)
        self.update_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.update_pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.update_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.update_pushButton.setStyleSheet("background-color: #228B22;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"border-radius: 5px;")
        self.update_pushButton.setObjectName("update_pushButton")
        self.horizontalLayout_3.addWidget(self.update_pushButton)
        self.cancel_pushButton = QtWidgets.QPushButton(parent=self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_pushButton.sizePolicy().hasHeightForWidth())
        self.cancel_pushButton.setSizePolicy(sizePolicy)
        self.cancel_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.cancel_pushButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cancel_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancel_pushButton.setStyleSheet("background-color: #DC3545;\n"
"font: 87 12pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"border-radius: 5px;")
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.horizontalLayout_3.addWidget(self.cancel_pushButton)
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Update Password:"))
        self.label_3.setText(_translate("Form", "Current Password:"))
        self.label_2.setText(_translate("Form", "New Password:"))
        self.update_pushButton.setText(_translate("Form", "Update"))
        self.cancel_pushButton.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
