# Form implementation generated from reading ui file 'username_requirements.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(400, 397)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.minLength_label = QtWidgets.QLabel(parent=Frame)
        self.minLength_label.setObjectName("minLength_label")
        self.verticalLayout.addWidget(self.minLength_label)
        self.constainsChar_label = QtWidgets.QLabel(parent=Frame)
        self.constainsChar_label.setObjectName("constainsChar_label")
        self.verticalLayout.addWidget(self.constainsChar_label)
        self.letterFirst_label = QtWidgets.QLabel(parent=Frame)
        self.letterFirst_label.setObjectName("letterFirst_label")
        self.verticalLayout.addWidget(self.letterFirst_label)
        self.noSpace_label = QtWidgets.QLabel(parent=Frame)
        self.noSpace_label.setObjectName("noSpace_label")
        self.verticalLayout.addWidget(self.noSpace_label)
        self.uniqueUser_label = QtWidgets.QLabel(parent=Frame)
        self.uniqueUser_label.setObjectName("uniqueUser_label")
        self.verticalLayout.addWidget(self.uniqueUser_label)
        self.uniqueUser_label.raise_()
        self.minLength_label.raise_()
        self.constainsChar_label.raise_()
        self.letterFirst_label.raise_()
        self.noSpace_label.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.minLength_label.setText(_translate("Frame", "Minimum Lenght"))
        self.constainsChar_label.setText(_translate("Frame", "Only contains (letters, numbers, underscore)"))
        self.letterFirst_label.setText(_translate("Frame", "Starts with a letter"))
        self.noSpace_label.setText(_translate("Frame", "No spaces"))
        self.uniqueUser_label.setText(_translate("Frame", "Unique Username"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec())
