# Form implementation generated from reading ui file 'admin_mainPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setMinimumSize(QtCore.QSize(1280, 720))
        Form.setStyleSheet("#Form{\n"
"background-color: #E3E6E9;\n"
"}")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 171, 721))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color: #0C0550")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(9, 9, 157, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #fff")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setGeometry(QtCore.QRect(0, 70, 171, 361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.users_btn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.users_btn.sizePolicy().hasHeightForWidth())
        self.users_btn.setSizePolicy(sizePolicy)
        self.users_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.users_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.users_btn.setStyleSheet("QPushButton {\n"
"padding: 10px 20px;\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"color: #fff;\n"
"  font: bold 10pt \"Inter\";\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #002688;\n"
"  color: #fff;\n"
"\n"
"  border-radius: 5px;\n"
"}\n"
"")
        self.users_btn.setObjectName("users_btn")
        self.gridLayout.addWidget(self.users_btn, 1, 0, 1, 1)
        self.settings_btn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_btn.sizePolicy().hasHeightForWidth())
        self.settings_btn.setSizePolicy(sizePolicy)
        self.settings_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.settings_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.settings_btn.setStyleSheet("QPushButton {\n"
"padding: 10px 20px;\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"color: #fff;\n"
"  font: bold 10pt \"Inter\";\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #002688;\n"
"  color: #fff;\n"
"\n"
"  border-radius: 5px;\n"
"}\n"
"")
        self.settings_btn.setObjectName("settings_btn")
        self.gridLayout.addWidget(self.settings_btn, 7, 0, 1, 1)
        self.reports_btn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reports_btn.sizePolicy().hasHeightForWidth())
        self.reports_btn.setSizePolicy(sizePolicy)
        self.reports_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.reports_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reports_btn.setStyleSheet("QPushButton {\n"
"padding: 10px 20px;\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"color: #fff;\n"
"  font: bold 10pt \"Inter\";\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #002688;\n"
"  color: #fff;\n"
"\n"
"  border-radius: 5px;\n"
"}\n"
"")
        self.reports_btn.setObjectName("reports_btn")
        self.gridLayout.addWidget(self.reports_btn, 5, 0, 1, 1)
        self.orders_btn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orders_btn.sizePolicy().hasHeightForWidth())
        self.orders_btn.setSizePolicy(sizePolicy)
        self.orders_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.orders_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.orders_btn.setStyleSheet("QPushButton {\n"
"padding: 10px 20px;\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"color: #fff;\n"
"  font: bold 10pt \"Inter\";\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #002688;\n"
"  color: #fff;\n"
"\n"
"  border-radius: 5px;\n"
"}\n"
"")
        self.orders_btn.setObjectName("orders_btn")
        self.gridLayout.addWidget(self.orders_btn, 3, 0, 1, 1)
        self.dashboard_btn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dashboard_btn.sizePolicy().hasHeightForWidth())
        self.dashboard_btn.setSizePolicy(sizePolicy)
        self.dashboard_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.dashboard_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.dashboard_btn.setStyleSheet("QPushButton {\n"
"padding: 10px 20px;\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"color: #fff;\n"
"  font: bold 10pt \"Inter\";\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #002688;\n"
"  color: #fff;\n"
"\n"
"  border-radius: 5px;\n"
"}\n"
"")
        self.dashboard_btn.setObjectName("dashboard_btn")
        self.gridLayout.addWidget(self.dashboard_btn, 0, 0, 1, 1)
        self.backup_btn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backup_btn.sizePolicy().hasHeightForWidth())
        self.backup_btn.setSizePolicy(sizePolicy)
        self.backup_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.backup_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.backup_btn.setStyleSheet("QPushButton {\n"
"padding: 10px 20px;\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"color: #fff;\n"
"  font: bold 10pt \"Inter\";\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #002688;\n"
"  color: #fff;\n"
"\n"
"  border-radius: 5px;\n"
"}\n"
"")
        self.backup_btn.setObjectName("backup_btn")
        self.gridLayout.addWidget(self.backup_btn, 8, 0, 1, 1)
        self.inventory_btn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inventory_btn.sizePolicy().hasHeightForWidth())
        self.inventory_btn.setSizePolicy(sizePolicy)
        self.inventory_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.inventory_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.inventory_btn.setStyleSheet("QPushButton {\n"
"padding: 10px 20px;\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"color: #fff;\n"
"  font: bold 10pt \"Inter\";\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #002688;\n"
"  color: #fff;\n"
"\n"
"  border-radius: 5px;\n"
"}\n"
"")
        self.inventory_btn.setObjectName("inventory_btn")
        self.gridLayout.addWidget(self.inventory_btn, 2, 0, 1, 1)
        self.customers_btn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customers_btn.sizePolicy().hasHeightForWidth())
        self.customers_btn.setSizePolicy(sizePolicy)
        self.customers_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.customers_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.customers_btn.setStyleSheet("QPushButton {\n"
"padding: 10px 20px;\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"color: #fff;\n"
"  font: bold 10pt \"Inter\";\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #002688;\n"
"  color: #fff;\n"
"\n"
"  border-radius: 5px;\n"
"}\n"
"")
        self.customers_btn.setObjectName("customers_btn")
        self.gridLayout.addWidget(self.customers_btn, 4, 0, 1, 1)
        self.activityLog_btn = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activityLog_btn.sizePolicy().hasHeightForWidth())
        self.activityLog_btn.setSizePolicy(sizePolicy)
        self.activityLog_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.activityLog_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.activityLog_btn.setStyleSheet("QPushButton {\n"
"padding: 10px 20px;\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\n"
"color: #fff;\n"
"  font: bold 10pt \"Inter\";\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #002688;\n"
"  color: #fff;\n"
"\n"
"  border-radius: 5px;\n"
"}\n"
"")
        self.activityLog_btn.setObjectName("activityLog_btn")
        self.gridLayout.addWidget(self.activityLog_btn, 6, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.frame_2 = QtWidgets.QFrame(parent=self.widget)
        self.frame_2.setGeometry(QtCore.QRect(0, 670, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.logout_btn = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logout_btn.sizePolicy().hasHeightForWidth())
        self.logout_btn.setSizePolicy(sizePolicy)
        self.logout_btn.setMinimumSize(QtCore.QSize(150, 35))
        self.logout_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logout_btn.setStyleSheet("background-color: #002688;\n"
"color: #fff;\n"
"font: 87 10pt \"Inter Black\";\n"
"border: 1px solid #1654F3;\n"
"border-radius: 5px;")
        self.logout_btn.setObjectName("logout_btn")
        self.gridLayout_2.addWidget(self.logout_btn, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.widget_2 = QtWidgets.QWidget(parent=Form)
        self.widget_2.setGeometry(QtCore.QRect(180, 10, 1091, 701))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("background-color: #fff")
        self.widget_2.setObjectName("widget_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Magtibay LPG Trading"))
        self.users_btn.setText(_translate("Form", "Accounts"))
        self.settings_btn.setText(_translate("Form", "Settings"))
        self.reports_btn.setText(_translate("Form", "Reports"))
        self.orders_btn.setText(_translate("Form", "Orders"))
        self.dashboard_btn.setText(_translate("Form", "Dashboard"))
        self.backup_btn.setText(_translate("Form", "Backup and Restore"))
        self.inventory_btn.setText(_translate("Form", "Inventory"))
        self.customers_btn.setText(_translate("Form", "Customers"))
        self.activityLog_btn.setText(_translate("Form", "Activity Logs"))
        self.logout_btn.setText(_translate("Form", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
