# Form implementation generated from reading ui file 'dashboardPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dashboardPage(object):
    def setupUi(self, dashboardPage):
        dashboardPage.setObjectName("dashboardPage")
        dashboardPage.resize(701, 480)
        self.frame = QtWidgets.QFrame(parent=dashboardPage)
        self.frame.setGeometry(QtCore.QRect(0, 0, 120, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 70, 120, 411))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.splitter = QtWidgets.QSplitter(parent=self.frame_2)
        self.splitter.setGeometry(QtCore.QRect(20, 30, 81, 221))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.dashboardBtn = QtWidgets.QPushButton(parent=self.splitter)
        self.dashboardBtn.setObjectName("dashboardBtn")
        self.accountsBtn = QtWidgets.QPushButton(parent=self.splitter)
        self.accountsBtn.setObjectName("accountsBtn")
        self.itemsBtn = QtWidgets.QPushButton(parent=self.splitter)
        self.itemsBtn.setObjectName("itemsBtn")
        self.activityLogsBtn = QtWidgets.QPushButton(parent=self.splitter)
        self.activityLogsBtn.setObjectName("activityLogsBtn")
        self.reportsBtn = QtWidgets.QPushButton(parent=self.splitter)
        self.reportsBtn.setObjectName("reportsBtn")
        self.notifBtn = QtWidgets.QPushButton(parent=self.splitter)
        self.notifBtn.setObjectName("notifBtn")
        self.logoutBtn = QtWidgets.QPushButton(parent=self.frame_2)
        self.logoutBtn.setGeometry(QtCore.QRect(20, 360, 81, 33))
        self.logoutBtn.setObjectName("logoutBtn")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 50, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_2.setObjectName("label_2")
        self.content_window = QtWidgets.QWidget(parent=dashboardPage)
        self.content_window.setGeometry(QtCore.QRect(120, 0, 581, 481))
        self.content_window.setObjectName("content_window")

        self.retranslateUi(dashboardPage)
        QtCore.QMetaObject.connectSlotsByName(dashboardPage)

    def retranslateUi(self, dashboardPage):
        _translate = QtCore.QCoreApplication.translate
        dashboardPage.setWindowTitle(_translate("dashboardPage", "Form"))
        self.dashboardBtn.setText(_translate("dashboardPage", "Dashboard"))
        self.accountsBtn.setText(_translate("dashboardPage", "Accounts"))
        self.itemsBtn.setText(_translate("dashboardPage", "Items"))
        self.activityLogsBtn.setText(_translate("dashboardPage", "Activity Logs"))
        self.reportsBtn.setText(_translate("dashboardPage", "Reports"))
        self.notifBtn.setText(_translate("dashboardPage", "Notification"))
        self.logoutBtn.setText(_translate("dashboardPage", "Logout"))
        self.label.setText(_translate("dashboardPage", "Admin"))
        self.label_2.setText(_translate("dashboardPage", "Owner Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dashboardPage = QtWidgets.QWidget()
    ui = Ui_dashboardPage()
    ui.setupUi(dashboardPage)
    dashboardPage.show()
    sys.exit(app.exec())
