# Form implementation generated from reading ui file 'menuPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.LoginBtn = QtWidgets.QPushButton(parent=Form)
        self.LoginBtn.setGeometry(QtCore.QRect(230, 150, 150, 23))
        self.LoginBtn.setObjectName("LoginBtn")
        self.SignupBtn = QtWidgets.QPushButton(parent=Form)
        self.SignupBtn.setGeometry(QtCore.QRect(220, 190, 150, 23))
        self.SignupBtn.setObjectName("SignupBtn")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 221, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LoginBtn.setText(_translate("Form", "LOGIN"))
        self.SignupBtn.setText(_translate("Form", "CREATE ACCOUNT"))
        self.label.setText(_translate("Form", "Menu Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
