# Form implementation generated from reading ui file 'newAccountPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewAccountPage(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.username = QtWidgets.QLineEdit(parent=Form)
        self.username.setGeometry(QtCore.QRect(110, 40, 113, 20))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=Form)
        self.password.setGeometry(QtCore.QRect(110, 70, 113, 20))
        self.password.setObjectName("password")
        self.createAccountBtn = QtWidgets.QPushButton(parent=Form)
        self.createAccountBtn.setGeometry(QtCore.QRect(110, 100, 111, 23))
        self.createAccountBtn.setObjectName("createAccountBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username.setPlaceholderText(_translate("Form", "Username"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.createAccountBtn.setText(_translate("Form", "Create Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_NewAccountPage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
