# Form implementation generated from reading ui file 'newitemsPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(753, 480)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 731, 461))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(110, 60, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(110, 150, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(110, 100, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(110, 260, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(110, 192, 81, 21))
        self.label_5.setObjectName("label_5")
        self.cylinder_size = QtWidgets.QComboBox(parent=self.widget)
        self.cylinder_size.setGeometry(QtCore.QRect(230, 100, 131, 22))
        self.cylinder_size.setObjectName("cylinder_size")
        self.quantity = QtWidgets.QSpinBox(parent=self.widget)
        self.quantity.setGeometry(QtCore.QRect(230, 150, 131, 22))
        self.quantity.setObjectName("quantity")
        self.product_name = QtWidgets.QLineEdit(parent=self.widget)
        self.product_name.setGeometry(QtCore.QRect(230, 60, 131, 21))
        self.product_name.setObjectName("product_name")
        self.timestamp = QtWidgets.QLineEdit(parent=self.widget)
        self.timestamp.setGeometry(QtCore.QRect(230, 260, 131, 21))
        self.timestamp.setObjectName("timestamp")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(180, 300, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.price = QtWidgets.QSpinBox(parent=self.widget)
        self.price.setGeometry(QtCore.QRect(230, 190, 131, 22))
        self.price.setObjectName("price")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(110, 220, 81, 21))
        self.label_6.setObjectName("label_6")
        self.status = QtWidgets.QComboBox(parent=self.widget)
        self.status.setGeometry(QtCore.QRect(230, 220, 131, 22))
        self.status.setObjectName("status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "PRODUCT NAME"))
        self.label_2.setText(_translate("Form", "QUANTITY"))
        self.label_3.setText(_translate("Form", "CYLINDER SIZE"))
        self.label_4.setText(_translate("Form", "TIMESTAMP"))
        self.label_5.setText(_translate("Form", "PRICE PER UNIT"))
        self.pushButton.setText(_translate("Form", "SAVE"))
        self.label_6.setText(_translate("Form", "STATUS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
