# Form implementation generated from reading ui file '.\orders_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1061, 655)
        Form.setStyleSheet("*{\n"
"color: #333333;\n"
"font: 10pt \"Noto Sans\";\n"
"background: transparent;\n"
"border: none;\n"
"}\n"
"#scrollArea{\n"
"border: none;\n"
"}\n"
"QLineEdit, QPlainTextEdit{\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"background-color: #fff;\n"
"}\n"
"QComboBox{\n"
"font: 10pt \"Inter\";\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px\n"
"}\n"
"QComboBox::drop-down{\n"
"border: none;\n"
"background: transparent;\n"
"}\n"
"QComboBox::down-arrow {\n"
"image: none;               \n"
"border: none;              \n"
"width: 0; height: 0;       \n"
"border-left: 5px solid none; \n"
"border-right: 5px solid none;\n"
"border-top: 7px solid #228B22; \n"
"margin: 0;\n"
"}\n"
"QSpinBox{\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setStyleSheet("#scrollArea{\n"
"border: none;\n"
"}\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F0F0F0;\n"
"                width: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-width: 14px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -560, 1044, 1215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_21 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_21.setStyleSheet("#frame_21{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_21)
        self.frame_22.setMinimumSize(QtCore.QSize(225, 90))
        self.frame_22.setStyleSheet("#frame_22{\n"
"background-color: #fff;\n"
"border: 1px solid #228B22;\n"
"border-radius: 5px;\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_22)
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_14.setMinimumSize(QtCore.QSize(0, 30))
        self.label_14.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_16.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_24)
        self.total_orders_label = QtWidgets.QLabel(parent=self.frame_22)
        self.total_orders_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"")
        self.total_orders_label.setObjectName("total_orders_label")
        self.verticalLayout.addWidget(self.total_orders_label)
        self.horizontalLayout_18.addWidget(self.frame_22, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_4.addWidget(self.frame_21)
        self.frame = QtWidgets.QFrame(parent=self.frame_2)
        self.frame.setMinimumSize(QtCore.QSize(670, 500))
        self.frame.setMaximumSize(QtCore.QSize(670, 500))
        self.frame.setStyleSheet("#frame{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        self.menu_scrollArea.setMaximumSize(QtCore.QSize(150, 16777215))
        self.menu_scrollArea.setWidgetResizable(True)
        self.menu_scrollArea.setObjectName("menu_scrollArea")
        self.menu_scrollArea_WidgetContents = QtWidgets.QWidget()
        self.menu_scrollArea_WidgetContents.setGeometry(QtCore.QRect(0, 0, 150, 482))
        self.menu_scrollArea_WidgetContents.setObjectName("menu_scrollArea_WidgetContents")
        self.menu_scrollArea.setWidget(self.menu_scrollArea_WidgetContents)
        self.horizontalLayout.addWidget(self.menu_scrollArea)
        self.products_scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        self.products_scrollArea.setMaximumSize(QtCore.QSize(500, 480))
        self.products_scrollArea.setStyleSheet("#products_scrollArea{\n"
"background-color: 808080;\n"
"border-radius: 5px;\n"
"}\n"
"QFrame{\n"
"background-color: blue;\n"
"}")
        self.products_scrollArea.setWidgetResizable(True)
        self.products_scrollArea.setObjectName("products_scrollArea")
        self.products_scrollArea_WidgetContents = QtWidgets.QWidget()
        self.products_scrollArea_WidgetContents.setGeometry(QtCore.QRect(0, 0, 497, 480))
        self.products_scrollArea_WidgetContents.setMaximumSize(QtCore.QSize(500, 480))
        self.products_scrollArea_WidgetContents.setObjectName("products_scrollArea_WidgetContents")
        self.products_scrollArea.setWidget(self.products_scrollArea_WidgetContents)
        self.horizontalLayout.addWidget(self.products_scrollArea)
        self.verticalLayout_4.addWidget(self.frame)
        self.orders_table_frame = QtWidgets.QFrame(parent=self.frame_2)
        self.orders_table_frame.setMinimumSize(QtCore.QSize(670, 0))
        self.orders_table_frame.setMaximumSize(QtCore.QSize(670, 16777215))
        self.orders_table_frame.setStyleSheet("#orders_table_frame{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.orders_table_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.orders_table_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.orders_table_frame.setObjectName("orders_table_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.orders_table_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_37 = QtWidgets.QFrame(parent=self.orders_table_frame)
        self.frame_37.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_37)
        self.label_19.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_26.addWidget(self.label_19)
        self.verticalLayout_3.addWidget(self.frame_37)
        self.frame_36 = QtWidgets.QFrame(parent=self.orders_table_frame)
        self.frame_36.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(5)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_36)
        self.label_22.setStyleSheet("font: 87 12pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_27.addWidget(self.label_22, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.backButton_frame = QtWidgets.QFrame(parent=self.frame_36)
        self.backButton_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backButton_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backButton_frame.setObjectName("backButton_frame")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.backButton_frame)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.back_pushButton = QtWidgets.QPushButton(parent=self.backButton_frame)
        self.back_pushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.back_pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.back_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back_pushButton.setStyleSheet("background-color: #fff;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #000;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;")
        self.back_pushButton.setObjectName("back_pushButton")
        self.horizontalLayout_28.addWidget(self.back_pushButton)
        self.horizontalLayout_27.addWidget(self.backButton_frame, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_3.addWidget(self.frame_36)
        self.orders_tableWidget = QtWidgets.QTableWidget(parent=self.orders_table_frame)
        self.orders_tableWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.orders_tableWidget.setObjectName("orders_tableWidget")
        self.orders_tableWidget.setColumnCount(0)
        self.orders_tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.orders_tableWidget)
        self.verticalLayout_4.addWidget(self.orders_table_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_17.addWidget(self.frame_2)
        self.frame_19 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_19.setStyleSheet("")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_23.setStyleSheet("#frame_23{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_25 = QtWidgets.QFrame(parent=self.frame_23)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_25)
        self.label_15.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.verticalLayout_7.addWidget(self.frame_25, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.recent_orders_scrollArea = QtWidgets.QScrollArea(parent=self.frame_23)
        self.recent_orders_scrollArea.setStyleSheet("#recent_orders_scrollArea{\n"
"background-color: #EAEAEA;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F0F0F0;\n"
"                width: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.recent_orders_scrollArea.setWidgetResizable(True)
        self.recent_orders_scrollArea.setObjectName("recent_orders_scrollArea")
        self.recent_orders_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.recent_orders_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 351, 252))
        self.recent_orders_scrollAreaWidgetContents.setObjectName("recent_orders_scrollAreaWidgetContents")
        self.recent_orders_scrollArea.setWidget(self.recent_orders_scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.recent_orders_scrollArea)
        self.recent_orders_scrollArea.raise_()
        self.frame_25.raise_()
        self.verticalLayout_6.addWidget(self.frame_23)
        self.frame_27 = QtWidgets.QFrame(parent=self.frame_19)
        self.frame_27.setStyleSheet("#frame_27{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_28 = QtWidgets.QFrame(parent=self.frame_27)
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_28)
        self.label_18.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.orders_quantity_label = QtWidgets.QLabel(parent=self.frame_28)
        self.orders_quantity_label.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.orders_quantity_label.setObjectName("orders_quantity_label")
        self.horizontalLayout_3.addWidget(self.orders_quantity_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_10.addWidget(self.frame_28)
        self.ordered_items_scrollArea = QtWidgets.QScrollArea(parent=self.frame_27)
        self.ordered_items_scrollArea.setMinimumSize(QtCore.QSize(350, 320))
        self.ordered_items_scrollArea.setStyleSheet("#ordered_items_scrollArea{\n"
"background-color: #EAEAEA;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F0F0F0;\n"
"                width: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.ordered_items_scrollArea.setWidgetResizable(True)
        self.ordered_items_scrollArea.setObjectName("ordered_items_scrollArea")
        self.orders_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.orders_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 351, 320))
        self.orders_scrollAreaWidgetContents.setObjectName("orders_scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.orders_scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ordered_items_scrollArea.setWidget(self.orders_scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.ordered_items_scrollArea, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_27)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.finalize_order_pushButton = QtWidgets.QPushButton(parent=self.frame_9)
        self.finalize_order_pushButton.setMinimumSize(QtCore.QSize(125, 30))
        self.finalize_order_pushButton.setMaximumSize(QtCore.QSize(125, 30))
        self.finalize_order_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.finalize_order_pushButton.setStyleSheet("background-color: #32CD32;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"border: none;\n"
"border-radius: 5px;")
        self.finalize_order_pushButton.setObjectName("finalize_order_pushButton")
        self.horizontalLayout_23.addWidget(self.finalize_order_pushButton)
        self.verticalLayout_10.addWidget(self.frame_9)
        self.verticalLayout_6.addWidget(self.frame_27)
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_19)
        self.frame_29.setStyleSheet("#frame_29{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_11.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_29)
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(5)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_30)
        self.label_20.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.verticalLayout_11.addWidget(self.frame_30, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_31 = QtWidgets.QFrame(parent=self.frame_29)
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_2.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.customer_name_lineEdit = QtWidgets.QLineEdit(parent=self.frame_4)
        self.customer_name_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.customer_name_lineEdit.setMaximumSize(QtCore.QSize(200, 30))
        self.customer_name_lineEdit.setObjectName("customer_name_lineEdit")
        self.horizontalLayout_4.addWidget(self.customer_name_lineEdit)
        self.customer_name_lineEdit.raise_()
        self.label_2.raise_()
        self.verticalLayout_12.addWidget(self.frame_4)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_7.setMinimumSize(QtCore.QSize(130, 0))
        self.label_7.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_7.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.payment_box = QtWidgets.QComboBox(parent=self.frame_8)
        self.payment_box.setMinimumSize(QtCore.QSize(200, 30))
        self.payment_box.setMaximumSize(QtCore.QSize(200, 30))
        self.payment_box.setStyleSheet("background-color: white")
        self.payment_box.setObjectName("payment_box")
        self.horizontalLayout_8.addWidget(self.payment_box)
        self.payment_box.raise_()
        self.label_7.raise_()
        self.verticalLayout_12.addWidget(self.frame_8)
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(5)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        self.label_3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_3.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.order_date_label = QtWidgets.QLabel(parent=self.frame_20)
        self.order_date_label.setMinimumSize(QtCore.QSize(0, 30))
        self.order_date_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.order_date_label.setObjectName("order_date_label")
        self.horizontalLayout_16.addWidget(self.order_date_label)
        self.verticalLayout_12.addWidget(self.frame_20)
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(5)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_26)
        self.label_17.setMinimumSize(QtCore.QSize(130, 0))
        self.label_17.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_17.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.delivery_address_plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame_26)
        self.delivery_address_plainTextEdit.setMinimumSize(QtCore.QSize(200, 65))
        self.delivery_address_plainTextEdit.setMaximumSize(QtCore.QSize(200, 120))
        self.delivery_address_plainTextEdit.setObjectName("delivery_address_plainTextEdit")
        self.horizontalLayout_20.addWidget(self.delivery_address_plainTextEdit)
        self.verticalLayout_12.addWidget(self.frame_26)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        self.label_8.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_8.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.status_box = QtWidgets.QComboBox(parent=self.frame_12)
        self.status_box.setMinimumSize(QtCore.QSize(200, 30))
        self.status_box.setMaximumSize(QtCore.QSize(200, 30))
        self.status_box.setStyleSheet("background-color: white")
        self.status_box.setObjectName("status_box")
        self.horizontalLayout_10.addWidget(self.status_box)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_12.setMinimumSize(QtCore.QSize(130, 0))
        self.label_12.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_12.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.contact_info = QtWidgets.QLineEdit(parent=self.frame_15)
        self.contact_info.setMinimumSize(QtCore.QSize(200, 30))
        self.contact_info.setMaximumSize(QtCore.QSize(200, 30))
        self.contact_info.setObjectName("contact_info")
        self.horizontalLayout_11.addWidget(self.contact_info)
        self.contact_info.raise_()
        self.label_12.raise_()
        self.verticalLayout_12.addWidget(self.frame_15)
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_10.setMinimumSize(QtCore.QSize(130, 0))
        self.label_10.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_10.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.note_input = QtWidgets.QPlainTextEdit(parent=self.frame_14)
        self.note_input.setMinimumSize(QtCore.QSize(200, 65))
        self.note_input.setMaximumSize(QtCore.QSize(200, 120))
        self.note_input.setObjectName("note_input")
        self.horizontalLayout_12.addWidget(self.note_input)
        self.verticalLayout_12.addWidget(self.frame_14)
        self.verticalLayout_11.addWidget(self.frame_31)
        self.verticalLayout_6.addWidget(self.frame_29)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_17.addWidget(self.frame_19)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_14.setText(_translate("Form", "Total Orders:"))
        self.label_16.setText(_translate("Form", "(Today)"))
        self.total_orders_label.setText(_translate("Form", "0"))
        self.label_19.setText(_translate("Form", "Orders Table"))
        self.label_22.setText(_translate("Form", "View Products"))
        self.back_pushButton.setText(_translate("Form", "Back"))
        self.label_15.setText(_translate("Form", "Recent Orders:"))
        self.label_18.setText(_translate("Form", "Ordered Items:"))
        self.orders_quantity_label.setText(_translate("Form", "0"))
        self.finalize_order_pushButton.setText(_translate("Form", "Confirm Order"))
        self.label_20.setText(_translate("Form", "Order Information:"))
        self.label_2.setText(_translate("Form", "Customer Name:"))
        self.label_7.setText(_translate("Form", "Payment Status:"))
        self.label_3.setText(_translate("Form", "Order Date:"))
        self.order_date_label.setText(_translate("Form", "TextLabel"))
        self.label_17.setText(_translate("Form", "Delivery Address:"))
        self.label_8.setText(_translate("Form", "Order Status:"))
        self.label_12.setText(_translate("Form", "Contact:"))
        self.label_10.setText(_translate("Form", "Remarks:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
