# Form implementation generated from reading ui file 'settings_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_settings_page(object):
    def setupUi(self, settings_page):
        settings_page.setObjectName("settings_page")
        settings_page.resize(716, 388)
        self.label = QtWidgets.QLabel(parent=settings_page)
        self.label.setGeometry(QtCore.QRect(10, 10, 150, 16))
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setObjectName("label")
        self.timeFormat_comboBox = QtWidgets.QComboBox(parent=settings_page)
        self.timeFormat_comboBox.setGeometry(QtCore.QRect(10, 30, 161, 22))
        self.timeFormat_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.timeFormat_comboBox.setObjectName("timeFormat_comboBox")

        self.retranslateUi(settings_page)
        QtCore.QMetaObject.connectSlotsByName(settings_page)

    def retranslateUi(self, settings_page):
        _translate = QtCore.QCoreApplication.translate
        settings_page.setWindowTitle(_translate("settings_page", "Form"))
        self.label.setText(_translate("settings_page", "Time Format"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    settings_page = QtWidgets.QWidget()
    ui = Ui_settings_page()
    ui.setupUi(settings_page)
    settings_page.show()
    sys.exit(app.exec())
