# Form implementation generated from reading ui file 'signupPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_signupPage(object):
    def setupUi(self, signupPage):
        signupPage.setObjectName("signupPage")
        signupPage.resize(640, 480)
        self.signupBtn = QtWidgets.QPushButton(parent=signupPage)
        self.signupBtn.setGeometry(QtCore.QRect(250, 280, 121, 23))
        self.signupBtn.setObjectName("signupBtn")
        self.label = QtWidgets.QLabel(parent=signupPage)
        self.label.setGeometry(QtCore.QRect(40, 60, 211, 16))
        self.label.setObjectName("label")
        self.menuBtn = QtWidgets.QPushButton(parent=signupPage)
        self.menuBtn.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.menuBtn.setObjectName("menuBtn")

        self.retranslateUi(signupPage)
        QtCore.QMetaObject.connectSlotsByName(signupPage)

    def retranslateUi(self, signupPage):
        _translate = QtCore.QCoreApplication.translate
        signupPage.setWindowTitle(_translate("signupPage", "Form"))
        self.signupBtn.setText(_translate("signupPage", "Create Account"))
        self.label.setText(_translate("signupPage", "Create Employee Account"))
        self.menuBtn.setText(_translate("signupPage", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signupPage = QtWidgets.QWidget()
    ui = Ui_signupPage()
    ui.setupUi(signupPage)
    signupPage.show()
    sys.exit(app.exec())
