# Form implementation generated from reading ui file 'ui_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(926, 986)
        Form.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setStyleSheet("#scrollArea{\n"
"border: none;\n"
"}\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"QScrollBar:vertical {\n"
" border: none;\n"
" background: #F0F0F0;\n"
"width: 10px;\n"
" margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1007, 1126))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_12 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_12.setStyleSheet("#frame_12{\n"
"background-color: #fff;\n"
"border-radius: 10px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame = QtWidgets.QFrame(parent=self.frame_12)
        self.frame.setMinimumSize(QtCore.QSize(200, 85))
        self.frame.setMaximumSize(QtCore.QSize(200, 85))
        self.frame.setStyleSheet("*{\n"
"background-color: transparent;\n"
"}\n"
"#frame{\n"
"background-color: #32CD32;\n"
"border: 1px solid #228B22;\n"
"border-radius: 5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("#frame_2{\n"
"color: #fff;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #fff;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label = QtWidgets.QLabel(parent=self.frame_22)
        self.label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.total_sales_label = QtWidgets.QLabel(parent=self.frame_22)
        self.total_sales_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.total_sales_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"")
        self.total_sales_label.setObjectName("total_sales_label")
        self.horizontalLayout_12.addWidget(self.total_sales_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_2.addWidget(self.frame_22, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout_7.addWidget(self.frame)
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_13.setMinimumSize(QtCore.QSize(200, 85))
        self.frame_13.setMaximumSize(QtCore.QSize(200, 85))
        self.frame_13.setStyleSheet("*{\n"
"background-color: transparent;\n"
"}\n"
"#frame_13{\n"
"background-color: #273B09;\n"
"border: 1px solid #002400;\n"
"border-radius: 5px;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_13)
        self.frame_15.setStyleSheet("#frame_2{\n"
"color: #fff;\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #fff;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_15)
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.total_orders_label = QtWidgets.QLabel(parent=self.frame_24)
        self.total_orders_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.total_orders_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"")
        self.total_orders_label.setObjectName("total_orders_label")
        self.horizontalLayout_14.addWidget(self.total_orders_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_13.addWidget(self.frame_24, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_12.addWidget(self.frame_15)
        self.horizontalLayout_7.addWidget(self.frame_13)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.frame_7 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_4.setMinimumSize(QtCore.QSize(500, 500))
        self.frame_4.setMaximumSize(QtCore.QSize(500, 500))
        self.frame_4.setStyleSheet("#frame_4{\n"
"background-color: #fff;\n"
"border-radius: 10px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_2.setStyleSheet("font: 87 14pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.sales_table_frame = QtWidgets.QFrame(parent=self.frame_4)
        self.sales_table_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sales_table_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sales_table_frame.setObjectName("sales_table_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sales_table_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.no_sales_frame = QtWidgets.QFrame(parent=self.sales_table_frame)
        self.no_sales_frame.setEnabled(True)
        self.no_sales_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.no_sales_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.no_sales_frame.setObjectName("no_sales_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.no_sales_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.no_sales_frame)
        self.label_5.setStyleSheet("font: 87 12pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_6.addWidget(self.no_sales_frame)
        self.sales_today_tableWidget = QtWidgets.QTableWidget(parent=self.sales_table_frame)
        self.sales_today_tableWidget.setMinimumSize(QtCore.QSize(480, 0))
        self.sales_today_tableWidget.setMaximumSize(QtCore.QSize(480, 16777215))
        self.sales_today_tableWidget.setStyleSheet("*{\n"
"font: 10pt \"Noto Sans\";\n"
"}\n"
"QTableWidget{\n"
"border: none;\n"
"gridline-color: transparent;\n"
"}\n"
"QHeaderView{\n"
"background-color: #228B22;\n"
"}\n"
"QHeaderView::section {\n"
"background-color: #228B22;\n"
"color: #fff;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"}")
        self.sales_today_tableWidget.setObjectName("sales_today_tableWidget")
        self.sales_today_tableWidget.setColumnCount(0)
        self.sales_today_tableWidget.setRowCount(0)
        self.verticalLayout_6.addWidget(self.sales_today_tableWidget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_5.addWidget(self.sales_table_frame)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_8.setStyleSheet("#frame_8{\n"
"background-color: transparent;\n"
"border-radius: 5px;\n"
"border: 1px solid #228B22;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.total_sale_table_label = QtWidgets.QLabel(parent=self.frame_8)
        self.total_sale_table_label.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #228B22;")
        self.total_sale_table_label.setObjectName("total_sale_table_label")
        self.horizontalLayout_3.addWidget(self.total_sale_table_label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_5.addWidget(self.frame_8, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(500, 500))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_5.setStyleSheet("#frame_5{\n"
"background-color: #fff;\n"
"border-radius: 10px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setStyleSheet("font: 87 14pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.verticalLayout_8.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.cylinderTypes_scrollArea = QtWidgets.QScrollArea(parent=self.frame_5)
        self.cylinderTypes_scrollArea.setStyleSheet("*{\n"
"border: none;\n"
"}\n"
"#cylinderTypes_scrollArea{\n"
"border: none;\n"
"}\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"QScrollBar:vertical {\n"
" border: none;\n"
" background: #F0F0F0;\n"
"width: 10px;\n"
" margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.cylinderTypes_scrollArea.setWidgetResizable(True)
        self.cylinderTypes_scrollArea.setObjectName("cylinderTypes_scrollArea")
        self.cylinderContainerLayout = QtWidgets.QWidget()
        self.cylinderContainerLayout.setGeometry(QtCore.QRect(0, 0, 482, 60))
        self.cylinderContainerLayout.setObjectName("cylinderContainerLayout")
        self.cylinderTypes_scrollArea.setWidget(self.cylinderContainerLayout)
        self.verticalLayout_8.addWidget(self.cylinderTypes_scrollArea, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_4.addWidget(self.frame_7, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_9 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_9.setStyleSheet("*{\n"
"none\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_9)
        self.frame_10.setMinimumSize(QtCore.QSize(500, 500))
        self.frame_10.setMaximumSize(QtCore.QSize(600, 500))
        self.frame_10.setStyleSheet("#frame_10{\n"
"background-color: #fff;\n"
"border-radius: 10px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_7.setStyleSheet("font: 87 14pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.verticalLayout_9.addWidget(self.frame_11, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.sizes_tabWidget = QtWidgets.QTabWidget(parent=self.frame_10)
        self.sizes_tabWidget.setMaximumSize(QtCore.QSize(500, 500))
        self.sizes_tabWidget.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.sizes_tabWidget.setObjectName("sizes_tabWidget")
        self.verticalLayout_9.addWidget(self.sizes_tabWidget)
        self.horizontalLayout_5.addWidget(self.frame_10, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        self.sizes_tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Total Sales Today:"))
        self.label.setText(_translate("Form", "₱"))
        self.total_sales_label.setText(_translate("Form", "0.00"))
        self.label_10.setText(_translate("Form", "Total Orders Today:"))
        self.total_orders_label.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "Today\'s Sales Breakdown"))
        self.label_5.setText(_translate("Form", "No Sales Recorded Today"))
        self.label_3.setText(_translate("Form", "Total Sale:"))
        self.total_sale_table_label.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "Products In Stock"))
        self.label_7.setText(_translate("Form", "Stock Level"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
