# Form implementation generated from reading ui file 'ui_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(713, 572)
        Form.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setStyleSheet("#scrollArea{\n"
"border: none;\n"
"}\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"QScrollBar:vertical {\n"
" border: none;\n"
" background: #F0F0F0;\n"
"width: 10px;\n"
" margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -52, 703, 701))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setMaximumSize(QtCore.QSize(160, 85))
        self.frame.setStyleSheet("*{\n"
"background-color: transparent;\n"
"}\n"
"#frame{\n"
"background-color: #32CD32;\n"
"border: 1px solid #228B22;\n"
"border-radius: 5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("#frame_2{\n"
"color: #fff;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #fff;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label = QtWidgets.QLabel(parent=self.frame_22)
        self.label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.total_sales_label = QtWidgets.QLabel(parent=self.frame_22)
        self.total_sales_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.total_sales_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"")
        self.total_sales_label.setObjectName("total_sales_label")
        self.horizontalLayout_12.addWidget(self.total_sales_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_2.addWidget(self.frame_22, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_7 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 600))
        self.frame_4.setMaximumSize(QtCore.QSize(420, 600))
        self.frame_4.setStyleSheet("#frame_4{\n"
"background-color: #fff;\n"
"border-radius: 10px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_2.setStyleSheet("font: 87 14pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.sales_table_frame = QtWidgets.QFrame(parent=self.frame_4)
        self.sales_table_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sales_table_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sales_table_frame.setObjectName("sales_table_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sales_table_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.no_sales_frame = QtWidgets.QFrame(parent=self.sales_table_frame)
        self.no_sales_frame.setEnabled(True)
        self.no_sales_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.no_sales_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.no_sales_frame.setObjectName("no_sales_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.no_sales_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.no_sales_frame)
        self.label_5.setStyleSheet("font: 87 12pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_6.addWidget(self.no_sales_frame)
        self.sales_today_tableWidget = QtWidgets.QTableWidget(parent=self.sales_table_frame)
        self.sales_today_tableWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.sales_today_tableWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.sales_today_tableWidget.setStyleSheet("*{\n"
"font: 10pt \"Noto Sans\";\n"
"}\n"
"QTableWidget{\n"
"border: none;\n"
"gridline-color: transparent;\n"
"}\n"
"QHeaderView{\n"
"background-color: #228B22;\n"
"}\n"
"QHeaderView::section {\n"
"background-color: #228B22;\n"
"color: #fff;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"}")
        self.sales_today_tableWidget.setObjectName("sales_today_tableWidget")
        self.sales_today_tableWidget.setColumnCount(0)
        self.sales_today_tableWidget.setRowCount(0)
        self.verticalLayout_6.addWidget(self.sales_today_tableWidget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_5.addWidget(self.sales_table_frame)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_8.setStyleSheet("#frame_8{\n"
"background-color: transparent;\n"
"border-radius: 5px;\n"
"border: 1px solid #228B22;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.total_sale_table_label = QtWidgets.QLabel(parent=self.frame_8)
        self.total_sale_table_label.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #228B22;")
        self.total_sale_table_label.setObjectName("total_sale_table_label")
        self.horizontalLayout_3.addWidget(self.total_sale_table_label, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_5.addWidget(self.frame_8, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_5.setStyleSheet("#frame_5{\n"
"background-color: #fff;\n"
"border-radius: 10px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"border: 1px solid;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 135, 49))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setStyleSheet("font: 87 14pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_4.addWidget(self.frame_7, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Total Sales Today:"))
        self.label.setText(_translate("Form", "₱"))
        self.total_sales_label.setText(_translate("Form", "0.00"))
        self.label_2.setText(_translate("Form", "Today\'s Sales Breakdown"))
        self.label_5.setText(_translate("Form", "No Sales Recorded Today"))
        self.label_3.setText(_translate("Form", "Total Sale:"))
        self.total_sale_table_label.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "PRODUCTS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
