# Form implementation generated from reading ui file '.\ui_item_frame.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(163, 71)
        Frame.setStyleSheet("*{\n"
"font: 10pt \"Noto Sans\";\n"
"background-color: transparent;\n"
"}\n"
"#Frame{\n"
"background-color: white;\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Frame)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.brand_label = QtWidgets.QLabel(parent=self.frame)
        self.brand_label.setStyleSheet("font: 87 12pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.brand_label.setObjectName("brand_label")
        self.horizontalLayout.addWidget(self.brand_label)
        self.size_label = QtWidgets.QLabel(parent=self.frame)
        self.size_label.setStyleSheet("color: #333333;\n"
"font: 63 10pt \"Noto Sans SemiBold\";")
        self.size_label.setObjectName("size_label")
        self.horizontalLayout.addWidget(self.size_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.price_label = QtWidgets.QLabel(parent=Frame)
        self.price_label.setStyleSheet("font: 63 11pt \"Noto Sans SemiBold\";\n"
"color: green;")
        self.price_label.setObjectName("price_label")
        self.verticalLayout.addWidget(self.price_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.brand_label.setText(_translate("Frame", "Brand"))
        self.size_label.setText(_translate("Frame", "Cylinder Size"))
        self.price_label.setText(_translate("Frame", "Price"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec())
