# Form implementation generated from reading ui file 'archive_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(791, 440)
        self.accounts_pushButton = QtWidgets.QPushButton(parent=Form)
        self.accounts_pushButton.setGeometry(QtCore.QRect(10, 10, 151, 23))
        self.accounts_pushButton.setObjectName("accounts_pushButton")
        self.products_pushButton = QtWidgets.QPushButton(parent=Form)
        self.products_pushButton.setGeometry(QtCore.QRect(10, 40, 151, 23))
        self.products_pushButton.setObjectName("products_pushButton")
        self.orders_pushButton = QtWidgets.QPushButton(parent=Form)
        self.orders_pushButton.setGeometry(QtCore.QRect(10, 70, 150, 23))
        self.orders_pushButton.setObjectName("orders_pushButton")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 771, 330))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.accounts_pushButton.setText(_translate("Form", "Accounts"))
        self.products_pushButton.setText(_translate("Form", "Products"))
        self.orders_pushButton.setText(_translate("Form", "Orders"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
