# Form implementation generated from reading ui file 'custom_listItem.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(505, 145)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label.setObjectName("label")
        self.schedID_label = QtWidgets.QLabel(parent=Form)
        self.schedID_label.setGeometry(QtCore.QRect(80, 10, 101, 16))
        self.schedID_label.setObjectName("schedID_label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.label_2.setObjectName("label_2")
        self.freq_label = QtWidgets.QLabel(parent=Form)
        self.freq_label.setGeometry(QtCore.QRect(120, 40, 101, 16))
        self.freq_label.setObjectName("freq_label")
        self.time_label = QtWidgets.QLabel(parent=Form)
        self.time_label.setGeometry(QtCore.QRect(120, 70, 101, 16))
        self.time_label.setObjectName("time_label")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_3.setObjectName("label_3")
        self.enableAutoBackup_checkBox = QtWidgets.QCheckBox(parent=Form)
        self.enableAutoBackup_checkBox.setGeometry(QtCore.QRect(10, 100, 141, 17))
        self.enableAutoBackup_checkBox.setObjectName("enableAutoBackup_checkBox")
        self.enableNotif_checkBox = QtWidgets.QCheckBox(parent=Form)
        self.enableNotif_checkBox.setGeometry(QtCore.QRect(10, 120, 171, 17))
        self.enableNotif_checkBox.setObjectName("enableNotif_checkBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Schedule ID:"))
        self.schedID_label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "Update Frequency:"))
        self.freq_label.setText(_translate("Form", "Update Frequency:"))
        self.time_label.setText(_translate("Form", "Backup Time:"))
        self.label_3.setText(_translate("Form", "Backup Time:"))
        self.enableAutoBackup_checkBox.setText(_translate("Form", "Enable Auto Backup"))
        self.enableNotif_checkBox.setText(_translate("Form", "Enable Notification"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
