# Form implementation generated from reading ui file 'daily_backup_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(461, 151)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.timeEdit = QtWidgets.QTimeEdit(parent=Form)
        self.timeEdit.setGeometry(QtCore.QRect(10, 30, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.enable_checkBox = QtWidgets.QCheckBox(parent=Form)
        self.enable_checkBox.setGeometry(QtCore.QRect(10, 60, 151, 17))
        self.enable_checkBox.setObjectName("enable_checkBox")
        self.enableNotif_checkBox = QtWidgets.QCheckBox(parent=Form)
        self.enableNotif_checkBox.setGeometry(QtCore.QRect(10, 80, 291, 17))
        self.enableNotif_checkBox.setObjectName("enableNotif_checkBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Daily Backup"))
        self.enable_checkBox.setText(_translate("Form", "Enable Daily Backup"))
        self.enableNotif_checkBox.setText(_translate("Form", "Send Notification on Backup Completion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
