# Form implementation generated from reading ui file 'new_order_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_newOrder_Form(object):
    def setupUi(self, newOrder_Form):
        newOrder_Form.setObjectName("newOrder_Form")
        newOrder_Form.resize(937, 730)
        self.label = QtWidgets.QLabel(parent=newOrder_Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=newOrder_Form)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=newOrder_Form)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=newOrder_Form)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=newOrder_Form)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.customerName_lineEdit = QtWidgets.QLineEdit(parent=newOrder_Form)
        self.customerName_lineEdit.setGeometry(QtCore.QRect(120, 30, 113, 20))
        self.customerName_lineEdit.setObjectName("customerName_lineEdit")
        self.contact_lineEdit = QtWidgets.QLineEdit(parent=newOrder_Form)
        self.contact_lineEdit.setGeometry(QtCore.QRect(120, 50, 113, 20))
        self.contact_lineEdit.setObjectName("contact_lineEdit")
        self.address_lineEdit = QtWidgets.QLineEdit(parent=newOrder_Form)
        self.address_lineEdit.setGeometry(QtCore.QRect(120, 70, 113, 20))
        self.address_lineEdit.setObjectName("address_lineEdit")
        self.label_6 = QtWidgets.QLabel(parent=newOrder_Form)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label_6.setObjectName("label_6")
        self.orderDate_label = QtWidgets.QLabel(parent=newOrder_Form)
        self.orderDate_label.setGeometry(QtCore.QRect(100, 110, 81, 16))
        self.orderDate_label.setObjectName("orderDate_label")
        self.addItem_pushButton = QtWidgets.QPushButton(parent=newOrder_Form)
        self.addItem_pushButton.setGeometry(QtCore.QRect(10, 130, 81, 23))
        self.addItem_pushButton.setObjectName("addItem_pushButton")
        self.products_tableWidget = QtWidgets.QTableWidget(parent=newOrder_Form)
        self.products_tableWidget.setGeometry(QtCore.QRect(100, 170, 811, 281))
        self.products_tableWidget.setObjectName("products_tableWidget")
        self.products_tableWidget.setColumnCount(0)
        self.products_tableWidget.setRowCount(0)
        self.createOrder_pushButton = QtWidgets.QPushButton(parent=newOrder_Form)
        self.createOrder_pushButton.setGeometry(QtCore.QRect(10, 160, 81, 23))
        self.createOrder_pushButton.setObjectName("createOrder_pushButton")
        self.label_7 = QtWidgets.QLabel(parent=newOrder_Form)
        self.label_7.setGeometry(QtCore.QRect(100, 150, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(newOrder_Form)
        QtCore.QMetaObject.connectSlotsByName(newOrder_Form)

    def retranslateUi(self, newOrder_Form):
        _translate = QtCore.QCoreApplication.translate
        newOrder_Form.setWindowTitle(_translate("newOrder_Form", "Create New Order"))
        self.label.setText(_translate("newOrder_Form", "Customer"))
        self.label_2.setText(_translate("newOrder_Form", "Customer Name:"))
        self.label_3.setText(_translate("newOrder_Form", "Contact:"))
        self.label_4.setText(_translate("newOrder_Form", "Delivery Address:"))
        self.label_5.setText(_translate("newOrder_Form", "Order"))
        self.label_6.setText(_translate("newOrder_Form", "Order Date:"))
        self.orderDate_label.setText(_translate("newOrder_Form", "Order Date:"))
        self.addItem_pushButton.setText(_translate("newOrder_Form", "Add Item"))
        self.createOrder_pushButton.setText(_translate("newOrder_Form", "Create Order"))
        self.label_7.setText(_translate("newOrder_Form", "Products Table:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    newOrder_Form = QtWidgets.QWidget()
    ui = Ui_newOrder_Form()
    ui.setupUi(newOrder_Form)
    newOrder_Form.show()
    sys.exit(app.exec())
