# Form implementation generated from reading ui file 'orders_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_orderPage_Form(object):
    def setupUi(self, orderPage_Form):
        orderPage_Form.setObjectName("orderPage_Form")
        orderPage_Form.resize(658, 443)
        self.createOrder_pushButton = QtWidgets.QPushButton(parent=orderPage_Form)
        self.createOrder_pushButton.setGeometry(QtCore.QRect(10, 10, 131, 23))
        self.createOrder_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.createOrder_pushButton.setObjectName("createOrder_pushButton")
        self.cancelOrder_pushButton = QtWidgets.QPushButton(parent=orderPage_Form)
        self.cancelOrder_pushButton.setGeometry(QtCore.QRect(10, 40, 131, 23))
        self.cancelOrder_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelOrder_pushButton.setObjectName("cancelOrder_pushButton")
        self.editOrder_pushButton = QtWidgets.QPushButton(parent=orderPage_Form)
        self.editOrder_pushButton.setGeometry(QtCore.QRect(10, 70, 131, 23))
        self.editOrder_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.editOrder_pushButton.setObjectName("editOrder_pushButton")
        self.orderHistory_pushButton = QtWidgets.QPushButton(parent=orderPage_Form)
        self.orderHistory_pushButton.setGeometry(QtCore.QRect(10, 100, 131, 23))
        self.orderHistory_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.orderHistory_pushButton.setObjectName("orderHistory_pushButton")

        self.retranslateUi(orderPage_Form)
        QtCore.QMetaObject.connectSlotsByName(orderPage_Form)

    def retranslateUi(self, orderPage_Form):
        _translate = QtCore.QCoreApplication.translate
        orderPage_Form.setWindowTitle(_translate("orderPage_Form", "Form"))
        self.createOrder_pushButton.setText(_translate("orderPage_Form", "Create New Order"))
        self.cancelOrder_pushButton.setText(_translate("orderPage_Form", "Cancel Order"))
        self.editOrder_pushButton.setText(_translate("orderPage_Form", "Edit Order"))
        self.orderHistory_pushButton.setText(_translate("orderPage_Form", "Order History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    orderPage_Form = QtWidgets.QWidget()
    ui = Ui_orderPage_Form()
    ui.setupUi(orderPage_Form)
    orderPage_Form.show()
    sys.exit(app.exec())
