# Form implementation generated from reading ui file 'prices_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(726, 625)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 718, 702))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.search_pushButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.search_pushButton.setObjectName("search_pushButton")
        self.verticalLayout_2.addWidget(self.search_pushButton)
        self.searchBar_lineEdit = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.searchBar_lineEdit.setObjectName("searchBar_lineEdit")
        self.verticalLayout_2.addWidget(self.searchBar_lineEdit)
        self.search_result_frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.search_result_frame.setStyleSheet("background-color: blue;")
        self.search_result_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.search_result_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.search_result_frame.setObjectName("search_result_frame")
        self.verticalLayout_2.addWidget(self.search_result_frame)
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.prices_tableWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.prices_tableWidget.setMinimumSize(QtCore.QSize(680, 300))
        self.prices_tableWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.prices_tableWidget.setObjectName("prices_tableWidget")
        self.prices_tableWidget.setColumnCount(0)
        self.prices_tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.prices_tableWidget)
        self.prev_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.prev_pushButton.setObjectName("prev_pushButton")
        self.verticalLayout_3.addWidget(self.prev_pushButton)
        self.next_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.next_pushButton.setObjectName("next_pushButton")
        self.verticalLayout_3.addWidget(self.next_pushButton)
        self.verticalLayout_2.addWidget(self.frame)
        self.price_history_pushButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.price_history_pushButton.setObjectName("price_history_pushButton")
        self.verticalLayout_2.addWidget(self.price_history_pushButton)
        self.price_history_tableWidget = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.price_history_tableWidget.setMinimumSize(QtCore.QSize(680, 200))
        self.price_history_tableWidget.setObjectName("price_history_tableWidget")
        self.price_history_tableWidget.setColumnCount(0)
        self.price_history_tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.price_history_tableWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.search_pushButton.setText(_translate("Form", "Search"))
        self.searchBar_lineEdit.setPlaceholderText(_translate("Form", "Type Product ID or Product Name Here"))
        self.prev_pushButton.setText(_translate("Form", "Previous"))
        self.next_pushButton.setText(_translate("Form", "Next"))
        self.price_history_pushButton.setText(_translate("Form", "View Price History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
