# Form implementation generated from reading ui file 'productTemplate.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(469, 96)
        self.productID_label = QtWidgets.QLabel(parent=Frame)
        self.productID_label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.productID_label.setObjectName("productID_label")
        self.productName_label = QtWidgets.QLabel(parent=Frame)
        self.productName_label.setGeometry(QtCore.QRect(90, 10, 71, 16))
        self.productName_label.setObjectName("productName_label")
        self.cylinderSize_label = QtWidgets.QLabel(parent=Frame)
        self.cylinderSize_label.setGeometry(QtCore.QRect(180, 10, 71, 16))
        self.cylinderSize_label.setObjectName("cylinderSize_label")
        self.price_label = QtWidgets.QLabel(parent=Frame)
        self.price_label.setGeometry(QtCore.QRect(260, 10, 71, 16))
        self.price_label.setObjectName("price_label")
        self.description_label = QtWidgets.QLabel(parent=Frame)
        self.description_label.setGeometry(QtCore.QRect(330, 10, 71, 16))
        self.description_label.setObjectName("description_label")
        self.availStock_label = QtWidgets.QLabel(parent=Frame)
        self.availStock_label.setGeometry(QtCore.QRect(10, 40, 111, 16))
        self.availStock_label.setObjectName("availStock_label")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.productID_label.setText(_translate("Frame", "Product ID"))
        self.productName_label.setText(_translate("Frame", "Product Name"))
        self.cylinderSize_label.setText(_translate("Frame", "Cylinder Size"))
        self.price_label.setText(_translate("Frame", "Price"))
        self.description_label.setText(_translate("Frame", "Description"))
        self.availStock_label.setText(_translate("Frame", "Available In Stock"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec())
