# Form implementation generated from reading ui file 'sales_report_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(709, 641)
        Form.setStyleSheet("*{\n"
"font: 10pt \"Noto Sans\";\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setStyleSheet("#scrollArea{\n"
"background-color: #EAEAEA;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F0F0F0;\n"
"                width: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(-398, 0, 1093, 1610))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_4.setStyleSheet("#frame_4{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_2.setMinimumSize(QtCore.QSize(225, 90))
        self.frame_2.setMaximumSize(QtCore.QSize(225, 16777215))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color: #fff;\n"
"border: 1px solid #228B22;\n"
"border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.revenue_month_label = QtWidgets.QLabel(parent=self.frame_2)
        self.revenue_month_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"")
        self.revenue_month_label.setObjectName("revenue_month_label")
        self.verticalLayout_2.addWidget(self.revenue_month_label)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=self.frame_4)
        self.frame.setMinimumSize(QtCore.QSize(225, 90))
        self.frame.setMaximumSize(QtCore.QSize(225, 16777215))
        self.frame.setStyleSheet("#frame{\n"
"background-color: #fff;\n"
"border: 1px solid #228B22;\n"
"border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.total_sales_label = QtWidgets.QLabel(parent=self.frame)
        self.total_sales_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"")
        self.total_sales_label.setObjectName("total_sales_label")
        self.verticalLayout_12.addWidget(self.total_sales_label)
        self.horizontalLayout_3.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_6.setStyleSheet("#frame_6{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_sales_report_pushButton = QtWidgets.QPushButton(parent=self.frame_16)
        self.create_sales_report_pushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.create_sales_report_pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.create_sales_report_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_sales_report_pushButton.setStyleSheet("background-color: #32CD32;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"border: none;\n"
"border-radius: 5px;")
        self.create_sales_report_pushButton.setObjectName("create_sales_report_pushButton")
        self.horizontalLayout.addWidget(self.create_sales_report_pushButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_12.addWidget(self.frame_16)
        self.verticalLayout_13.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_8.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_7.setStyleSheet("border: 1px solid #000;\n"
"border-radius: 5px;\n"
"background-color: #fff;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.search_lineEdit = QtWidgets.QLineEdit(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_lineEdit.sizePolicy().hasHeightForWidth())
        self.search_lineEdit.setSizePolicy(sizePolicy)
        self.search_lineEdit.setMinimumSize(QtCore.QSize(250, 0))
        self.search_lineEdit.setStyleSheet("border: none;\n"
"padding: 5px;\n"
"color: #000;")
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.horizontalLayout_8.addWidget(self.search_lineEdit)
        self.search_pushButton = QtWidgets.QPushButton(parent=self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_pushButton.sizePolicy().hasHeightForWidth())
        self.search_pushButton.setSizePolicy(sizePolicy)
        self.search_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.search_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.search_pushButton.setStyleSheet("border: none;\n"
"background-color: #fff;")
        self.search_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../resources/icons/black-theme/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_pushButton.setIcon(icon)
        self.search_pushButton.setObjectName("search_pushButton")
        self.horizontalLayout_8.addWidget(self.search_pushButton)
        self.horizontalLayout_2.addWidget(self.frame_7, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_5.setStyleSheet("font: 87 12pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.backButton_frame = QtWidgets.QFrame(parent=self.frame_14)
        self.backButton_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backButton_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backButton_frame.setObjectName("backButton_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.backButton_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.back_pushButton = QtWidgets.QPushButton(parent=self.backButton_frame)
        self.back_pushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.back_pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.back_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back_pushButton.setStyleSheet("background-color: #fff;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #000;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;")
        self.back_pushButton.setObjectName("back_pushButton")
        self.horizontalLayout_4.addWidget(self.back_pushButton)
        self.horizontalLayout_9.addWidget(self.backButton_frame, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_13.addWidget(self.frame_14)
        self.sales_tableWidget = QtWidgets.QTableWidget(parent=self.frame_6)
        self.sales_tableWidget.setMinimumSize(QtCore.QSize(0, 600))
        self.sales_tableWidget.setMaximumSize(QtCore.QSize(16777215, 600))
        self.sales_tableWidget.setObjectName("sales_tableWidget")
        self.sales_tableWidget.setColumnCount(0)
        self.sales_tableWidget.setRowCount(0)
        self.verticalLayout_13.addWidget(self.sales_tableWidget)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.prev_pushButton = QtWidgets.QPushButton(parent=self.frame_15)
        self.prev_pushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.prev_pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.prev_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.prev_pushButton.setStyleSheet("background-color: #fff;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #000;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;")
        self.prev_pushButton.setObjectName("prev_pushButton")
        self.horizontalLayout_11.addWidget(self.prev_pushButton)
        self.next_pushButton = QtWidgets.QPushButton(parent=self.frame_15)
        self.next_pushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.next_pushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.next_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.next_pushButton.setStyleSheet("background-color: #fff;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #000;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;")
        self.next_pushButton.setObjectName("next_pushButton")
        self.horizontalLayout_11.addWidget(self.next_pushButton)
        self.verticalLayout_13.addWidget(self.frame_15, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_10 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 700))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_8.setStyleSheet("#frame_8{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_3.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.frame_8)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(700, 0))
        self.scrollArea_2.setStyleSheet("#scrollArea_2{\n"
"border: none;\n"
"}")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 700, 641))
        self.scrollAreaWidgetContents_2.setStyleSheet("border: none;")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sales_trend_frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.sales_trend_frame.setMinimumSize(QtCore.QSize(700, 400))
        self.sales_trend_frame.setStyleSheet("background-color: white;")
        self.sales_trend_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sales_trend_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.sales_trend_frame.setObjectName("sales_trend_frame")
        self.verticalLayout_6.addWidget(self.sales_trend_frame)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 500))
        self.frame_9.setStyleSheet("#frame_9{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_9)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_4.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.best_selling_label = QtWidgets.QLabel(parent=self.frame_12)
        self.best_selling_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"")
        self.best_selling_label.setObjectName("best_selling_label")
        self.horizontalLayout_7.addWidget(self.best_selling_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_5.addWidget(self.frame_12, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.best_selling_scrollArea = QtWidgets.QScrollArea(parent=self.frame_9)
        self.best_selling_scrollArea.setMinimumSize(QtCore.QSize(350, 250))
        self.best_selling_scrollArea.setStyleSheet("#best_selling_scrollArea{\n"
"background-color: #EAEAEA;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F0F0F0;\n"
"                width: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.best_selling_scrollArea.setWidgetResizable(True)
        self.best_selling_scrollArea.setObjectName("best_selling_scrollArea")
        self.best_selling_prod_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.best_selling_prod_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 350, 622))
        self.best_selling_prod_scrollAreaWidgetContents.setObjectName("best_selling_prod_scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.best_selling_prod_scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.best_selling_scrollArea.setWidget(self.best_selling_prod_scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.best_selling_scrollArea)
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Revenue This Month:"))
        self.revenue_month_label.setText(_translate("Form", "0"))
        self.label.setText(_translate("Form", "Total Sales Today:"))
        self.total_sales_label.setText(_translate("Form", "0"))
        self.create_sales_report_pushButton.setText(_translate("Form", "Create Sales Report"))
        self.label_8.setText(_translate("Form", "Sales Table"))
        self.search_lineEdit.setPlaceholderText(_translate("Form", "Search Sale ID"))
        self.label_5.setText(_translate("Form", "View Products"))
        self.back_pushButton.setText(_translate("Form", "Back"))
        self.prev_pushButton.setText(_translate("Form", "Previous"))
        self.next_pushButton.setText(_translate("Form", "Next"))
        self.label_3.setText(_translate("Form", "Sales Trend Chart"))
        self.label_4.setText(_translate("Form", "Best Selling:"))
        self.best_selling_label.setText(_translate("Form", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
