# Form implementation generated from reading ui file 'weekly_backup_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 330)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.timeEdit = QtWidgets.QTimeEdit(parent=Form)
        self.timeEdit.setGeometry(QtCore.QRect(10, 150, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.enable_checkBox = QtWidgets.QCheckBox(parent=Form)
        self.enable_checkBox.setGeometry(QtCore.QRect(10, 180, 151, 17))
        self.enable_checkBox.setObjectName("enable_checkBox")
        self.enableNotif_checkBox = QtWidgets.QCheckBox(parent=Form)
        self.enableNotif_checkBox.setGeometry(QtCore.QRect(10, 200, 291, 17))
        self.enableNotif_checkBox.setObjectName("enableNotif_checkBox")
        self.oneDay_radioButton = QtWidgets.QRadioButton(parent=Form)
        self.oneDay_radioButton.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.oneDay_radioButton.setObjectName("oneDay_radioButton")
        self.multipleDays_radioButton = QtWidgets.QRadioButton(parent=Form)
        self.multipleDays_radioButton.setGeometry(QtCore.QRect(90, 30, 91, 17))
        self.multipleDays_radioButton.setObjectName("multipleDays_radioButton")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(10, 50, 621, 103))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.oneDay_frame = QtWidgets.QFrame(parent=self.frame)
        self.oneDay_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.oneDay_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.oneDay_frame.setObjectName("oneDay_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.oneDay_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.oneDay_comboBox = QtWidgets.QComboBox(parent=self.oneDay_frame)
        self.oneDay_comboBox.setObjectName("oneDay_comboBox")
        self.horizontalLayout.addWidget(self.oneDay_comboBox)
        self.verticalLayout.addWidget(self.oneDay_frame)
        self.multipleDay_frame = QtWidgets.QFrame(parent=self.frame)
        self.multipleDay_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.multipleDay_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.multipleDay_frame.setObjectName("multipleDay_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.multipleDay_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sunday_checkBox = QtWidgets.QCheckBox(parent=self.multipleDay_frame)
        self.sunday_checkBox.setObjectName("sunday_checkBox")
        self.horizontalLayout_2.addWidget(self.sunday_checkBox)
        self.monday_checkBox = QtWidgets.QCheckBox(parent=self.multipleDay_frame)
        self.monday_checkBox.setObjectName("monday_checkBox")
        self.horizontalLayout_2.addWidget(self.monday_checkBox)
        self.tues_checkBox = QtWidgets.QCheckBox(parent=self.multipleDay_frame)
        self.tues_checkBox.setObjectName("tues_checkBox")
        self.horizontalLayout_2.addWidget(self.tues_checkBox)
        self.wed_checkBox = QtWidgets.QCheckBox(parent=self.multipleDay_frame)
        self.wed_checkBox.setObjectName("wed_checkBox")
        self.horizontalLayout_2.addWidget(self.wed_checkBox)
        self.thurs_checkBox = QtWidgets.QCheckBox(parent=self.multipleDay_frame)
        self.thurs_checkBox.setObjectName("thurs_checkBox")
        self.horizontalLayout_2.addWidget(self.thurs_checkBox)
        self.fri_checkBox = QtWidgets.QCheckBox(parent=self.multipleDay_frame)
        self.fri_checkBox.setObjectName("fri_checkBox")
        self.horizontalLayout_2.addWidget(self.fri_checkBox)
        self.sat_checkBox = QtWidgets.QCheckBox(parent=self.multipleDay_frame)
        self.sat_checkBox.setObjectName("sat_checkBox")
        self.horizontalLayout_2.addWidget(self.sat_checkBox)
        self.verticalLayout.addWidget(self.multipleDay_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Weekly Backup"))
        self.enable_checkBox.setText(_translate("Form", "Enable Daily Backup"))
        self.enableNotif_checkBox.setText(_translate("Form", "Send Notification on Backup Completion"))
        self.oneDay_radioButton.setText(_translate("Form", "One Day"))
        self.multipleDays_radioButton.setText(_translate("Form", "Multiple Days"))
        self.sunday_checkBox.setText(_translate("Form", "Sunday"))
        self.monday_checkBox.setText(_translate("Form", "Monday"))
        self.tues_checkBox.setText(_translate("Form", "Tuesday"))
        self.wed_checkBox.setText(_translate("Form", "Wednesday"))
        self.thurs_checkBox.setText(_translate("Form", "Thursday"))
        self.fri_checkBox.setText(_translate("Form", "Friday"))
        self.sat_checkBox.setText(_translate("Form", "Saturday"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
