# Form implementation generated from reading ui file 'login_mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_mainWindow(object):
    def setupUi(self, login_mainWindow):
        login_mainWindow.setObjectName("login_mainWindow")
        login_mainWindow.resize(340, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_mainWindow.sizePolicy().hasHeightForWidth())
        login_mainWindow.setSizePolicy(sizePolicy)
        login_mainWindow.setMinimumSize(QtCore.QSize(340, 550))
        login_mainWindow.setMaximumSize(QtCore.QSize(340, 550))
        login_mainWindow.setBaseSize(QtCore.QSize(340, 550))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(6)
        login_mainWindow.setFont(font)
        login_mainWindow.setStyleSheet("background-color: #fff")
        login_mainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=login_mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(100, 250, 141, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMinimumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.login_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.login_btn.setStyleSheet("width: 130px;\n"
"font: 87 10pt \"Arial Black\";\n"
"background-color: #1654F3;\n"
"color: #fff;\n"
"font-weight: bold;\n"
"border-radius: 5px;")
        self.login_btn.setObjectName("login_btn")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 70, 341, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout_2.setStretch(1, 10)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 160, 204, 87))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.username = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username.sizePolicy().hasHeightForWidth())
        self.username.setSizePolicy(sizePolicy)
        self.username.setMinimumSize(QtCore.QSize(200, 30))
        self.username.setBaseSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.username.setStyleSheet("border: 2px solid #949494;\n"
"background-color: #fff;\n"
"width: 200px;\n"
"height: 30px;\n"
"border-radius: 5px;\n"
"color: #949494;\n"
"padding: 0px 5px;")
        self.username.setText("")
        self.username.setClearButtonEnabled(False)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password.sizePolicy().hasHeightForWidth())
        self.password.setSizePolicy(sizePolicy)
        self.password.setMinimumSize(QtCore.QSize(200, 30))
        self.password.setBaseSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.password.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.password.setStyleSheet("border: 2px solid #949494;\n"
"background-color: #fff;\n"
"width: 200px;\n"
"height: 30px;\n"
"border-radius: 5px;\n"
"color: #949494;\n"
"padding: 0px 5px;")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        login_mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_mainWindow)
        QtCore.QMetaObject.connectSlotsByName(login_mainWindow)

    def retranslateUi(self, login_mainWindow):
        _translate = QtCore.QCoreApplication.translate
        login_mainWindow.setWindowTitle(_translate("login_mainWindow", "Login"))
        self.login_btn.setText(_translate("login_mainWindow", "LOGIN"))
        self.label.setText(_translate("login_mainWindow", "WELCOME!"))
        self.label_2.setText(_translate("login_mainWindow", "Login to your account"))
        self.username.setPlaceholderText(_translate("login_mainWindow", "Username"))
        self.password.setPlaceholderText(_translate("login_mainWindow", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_mainWindow = QtWidgets.QMainWindow()
    ui = Ui_login_mainWindow()
    ui.setupUi(login_mainWindow)
    login_mainWindow.show()
    sys.exit(app.exec())
