# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(824, 599)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_5.setStyleSheet("#frame_4{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"border: none;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_3.setStyleSheet("font: 63 15pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_3.addWidget(self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_7.setStyleSheet("#frame_7{\n"
"background-color: #32CD32;\n"
"border: 1px solid #228B22;\n"
"border-radius: 5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_4.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #fff;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_23)
        self.label_5.setStyleSheet("font: 63 8pt \"Noto Sans SemiBold\";\n"
"color: #fff;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_4.addWidget(self.frame_23, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label = QtWidgets.QLabel(parent=self.frame_22)
        self.label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.total_sales_label = QtWidgets.QLabel(parent=self.frame_22)
        self.total_sales_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.total_sales_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"")
        self.total_sales_label.setObjectName("total_sales_label")
        self.horizontalLayout_12.addWidget(self.total_sales_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_4.addWidget(self.frame_22, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout_5.addWidget(self.frame_7, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_8.setStyleSheet("#frame_8{\n"
"background-color: #fff;\n"
"border: 1px solid #228B22;\n"
"border-radius: 5px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_6.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.total_orders_label = QtWidgets.QLabel(parent=self.frame_8)
        self.total_orders_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.total_orders_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"")
        self.total_orders_label.setObjectName("total_orders_label")
        self.verticalLayout_5.addWidget(self.total_orders_label)
        self.horizontalLayout_5.addWidget(self.frame_8, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_9.setStyleSheet("#frame_9{\n"
"background-color: #fff;\n"
"border: 1px solid #228B22;\n"
"border-radius: 5px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_8.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.totalItemStock_label = QtWidgets.QLabel(parent=self.frame_9)
        self.totalItemStock_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.totalItemStock_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"")
        self.totalItemStock_label.setObjectName("totalItemStock_label")
        self.verticalLayout_6.addWidget(self.totalItemStock_label)
        self.horizontalLayout_5.addWidget(self.frame_9, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_11.setStyleSheet("#frame_11{\n"
"background-color: #fff;\n"
"border: 1px solid #FF7043;\n"
"border-radius: 5px;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_10.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.low_stock_label = QtWidgets.QLabel(parent=self.frame_11)
        self.low_stock_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.low_stock_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"")
        self.low_stock_label.setObjectName("low_stock_label")
        self.verticalLayout_8.addWidget(self.low_stock_label)
        self.horizontalLayout_5.addWidget(self.frame_11, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_3.addWidget(self.frame_10, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_7.addWidget(self.frame_5, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setStyleSheet("background-color:#ffffff;\n"
"border:none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_10.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_4)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 803, 623))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_12 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_12.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_14.setMinimumSize(QtCore.QSize(450, 300))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_14.setStyleSheet("#frame_14{\n"
"background-color: #fff;\n"
"border-radius: 10px;\n"
"border:1px solid gray;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_9.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_11.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.cylinderTypes_scrollArea = QtWidgets.QScrollArea(parent=self.frame_14)
        self.cylinderTypes_scrollArea.setMinimumSize(QtCore.QSize(300, 250))
        self.cylinderTypes_scrollArea.setMaximumSize(QtCore.QSize(16777215, 360))
        self.cylinderTypes_scrollArea.setStyleSheet("*{\n"
"background-color: #fff;\n"
"}\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F0F0F0;\n"
"                width: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 10px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.cylinderTypes_scrollArea.setWidgetResizable(True)
        self.cylinderTypes_scrollArea.setObjectName("cylinderTypes_scrollArea")
        self.cylinderContainerLayout = QtWidgets.QWidget()
        self.cylinderContainerLayout.setGeometry(QtCore.QRect(0, 0, 430, 251))
        self.cylinderContainerLayout.setObjectName("cylinderContainerLayout")
        self.cylinderTypes_scrollArea.setWidget(self.cylinderContainerLayout)
        self.verticalLayout_9.addWidget(self.cylinderTypes_scrollArea)
        self.verticalLayout_16.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setMinimumSize(QtCore.QSize(450, 300))
        self.frame_15.setMaximumSize(QtCore.QSize(600, 300))
        self.frame_15.setStyleSheet("#frame_15{\n"
"background-color: #fff;\n"
"border-radius: 10px;\n"
"border:1px solid gray;\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_18.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_15)
        self.frame_17.setStyleSheet("*{\n"
"background-color: transparent;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_17)
        self.label_12.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_17)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        self.label_14.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.daily_order_label = QtWidgets.QLabel(parent=self.frame_16)
        self.daily_order_label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.daily_order_label.setObjectName("daily_order_label")
        self.horizontalLayout_6.addWidget(self.daily_order_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_11.addWidget(self.frame_16)
        self.frame_18 = QtWidgets.QFrame(parent=self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_18)
        self.label_16.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.weekly_order_label = QtWidgets.QLabel(parent=self.frame_18)
        self.weekly_order_label.setObjectName("weekly_order_label")
        self.horizontalLayout_7.addWidget(self.weekly_order_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_11.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(parent=self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_19)
        self.label_18.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.monthly_order_label = QtWidgets.QLabel(parent=self.frame_19)
        self.monthly_order_label.setObjectName("monthly_order_label")
        self.horizontalLayout_8.addWidget(self.monthly_order_label, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_11.addWidget(self.frame_19)
        self.verticalLayout_18.addWidget(self.frame_17)
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_15)
        self.frame_20.setStyleSheet("#frame_20{\n"
"border:1px solid gray;\n"
"}")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frame_20)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setStyleSheet("background-color: transparent;\n"
"color: #000;\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.completed_order_listWidget = QtWidgets.QListWidget(parent=self.tab)
        self.completed_order_listWidget.setObjectName("completed_order_listWidget")
        self.verticalLayout_13.addWidget(self.completed_order_listWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pending_order_listWidget = QtWidgets.QListWidget(parent=self.tab_3)
        self.pending_order_listWidget.setStyleSheet("background-color: transparent;\n"
"color: #000;")
        self.pending_order_listWidget.setObjectName("pending_order_listWidget")
        self.verticalLayout_14.addWidget(self.pending_order_listWidget)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.cancelled_order_listWidget = QtWidgets.QListWidget(parent=self.tab_2)
        self.cancelled_order_listWidget.setObjectName("cancelled_order_listWidget")
        self.verticalLayout_15.addWidget(self.cancelled_order_listWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_12.addWidget(self.tabWidget)
        self.verticalLayout_18.addWidget(self.frame_20)
        self.verticalLayout_16.addWidget(self.frame_15)
        self.horizontalLayout_2.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_13.setStyleSheet("#frame_13{\n"
"background-color:rgb(255, 255, 255);\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_20.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_20.setObjectName("label_20")
        self.verticalLayout_17.addWidget(self.label_20)
        self.stockChart_frame = QtWidgets.QFrame(parent=self.frame_13)
        self.stockChart_frame.setMinimumSize(QtCore.QSize(0, 500))
        self.stockChart_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.stockChart_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.stockChart_frame.setObjectName("stockChart_frame")
        self.verticalLayout_17.addWidget(self.stockChart_frame)
        self.horizontalLayout_2.addWidget(self.frame_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Overview:"))
        self.label_4.setText(_translate("Form", "Total Sales:"))
        self.label_5.setText(_translate("Form", "(Today)"))
        self.label.setText(_translate("Form", "₱"))
        self.total_sales_label.setText(_translate("Form", "0.00"))
        self.label_6.setText(_translate("Form", "Total Orders:"))
        self.total_orders_label.setText(_translate("Form", "0.00"))
        self.label_8.setText(_translate("Form", "Total Products In Stock:"))
        self.totalItemStock_label.setText(_translate("Form", "0"))
        self.label_10.setText(_translate("Form", "Low Stock:"))
        self.low_stock_label.setText(_translate("Form", "0"))
        self.label_11.setText(_translate("Form", "Products In Stock:"))
        self.label_12.setText(_translate("Form", "Orders Summary:"))
        self.label_14.setText(_translate("Form", "Daily:"))
        self.daily_order_label.setText(_translate("Form", "0"))
        self.label_16.setText(_translate("Form", "Weekly:"))
        self.weekly_order_label.setText(_translate("Form", "0"))
        self.label_18.setText(_translate("Form", "Monthly:"))
        self.monthly_order_label.setText(_translate("Form", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Completed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Processing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Cancelled"))
        self.label_20.setText(_translate("Form", "Stock Levels"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
