# Form implementation generated from reading ui file 'orders_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(660, 727)
        Form.setStyleSheet("*{\n"
"color: #333333;\n"
"font: 10pt \"Noto Sans\";\n"
"background: transparent;\n"
"}\n"
"#scrollArea{\n"
"border: none;\n"
"}\n"
"QLineEdit, QPlainTextEdit{\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"background-color: #fff;\n"
"}\n"
"QComboBox{\n"
"font: 10pt \"Inter\";\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px\n"
"}\n"
"QComboBox::drop-down{\n"
"border: none;\n"
"background: transparent;\n"
"}\n"
"QComboBox::down-arrow {\n"
"image: none;               \n"
"border: none;              \n"
"width: 0; height: 0;       \n"
"border-left: 5px solid none; \n"
"border-right: 5px solid none;\n"
"border-top: 7px solid #228B22; \n"
"margin: 0;\n"
"}\n"
"QSpinBox{\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"}")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(-407, 0, 1100, 956))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(parent=self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_5.addWidget(self.frame)
        self.frame_21 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_21.setStyleSheet("#frame_21{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_21)
        self.frame_22.setMinimumSize(QtCore.QSize(225, 90))
        self.frame_22.setStyleSheet("#frame_22{\n"
"background-color: #fff;\n"
"border: 1px solid #228B22;\n"
"border-radius: 5px;\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_22)
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_14.setMinimumSize(QtCore.QSize(0, 30))
        self.label_14.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_16.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_19.addWidget(self.label_16, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_24)
        self.total_orders_label = QtWidgets.QLabel(parent=self.frame_22)
        self.total_orders_label.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;\n"
"")
        self.total_orders_label.setObjectName("total_orders_label")
        self.verticalLayout.addWidget(self.total_orders_label)
        self.horizontalLayout_18.addWidget(self.frame_22, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout_5.addWidget(self.frame_21)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setStyleSheet("#frame_3{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.view_order_pushButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.view_order_pushButton.setMinimumSize(QtCore.QSize(125, 30))
        self.view_order_pushButton.setMaximumSize(QtCore.QSize(125, 30))
        self.view_order_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.view_order_pushButton.setStyleSheet("background-color: #32CD32;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"border: none;\n"
"border-radius: 5px;")
        self.view_order_pushButton.setObjectName("view_order_pushButton")
        self.horizontalLayout_2.addWidget(self.view_order_pushButton)
        self.order_history_pushButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.order_history_pushButton.setMinimumSize(QtCore.QSize(125, 30))
        self.order_history_pushButton.setMaximumSize(QtCore.QSize(125, 30))
        self.order_history_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.order_history_pushButton.setStyleSheet("background-color: #fff;\n"
"border: 1px solid #000;\n"
"border-radius: 5px;\n"
"padding: 5px;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #1E1E1E;")
        self.order_history_pushButton.setObjectName("order_history_pushButton")
        self.horizontalLayout_2.addWidget(self.order_history_pushButton)
        self.verticalLayout_5.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.frame_18 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_18.setStyleSheet("")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_18)
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_29.setStyleSheet("#frame_29{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_11.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_29)
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_30)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(5)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_30)
        self.label_20.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.verticalLayout_11.addWidget(self.frame_30, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_31 = QtWidgets.QFrame(parent=self.frame_29)
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_2.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.customer_name_lineEdit = QtWidgets.QLineEdit(parent=self.frame_4)
        self.customer_name_lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.customer_name_lineEdit.setMaximumSize(QtCore.QSize(200, 30))
        self.customer_name_lineEdit.setObjectName("customer_name_lineEdit")
        self.horizontalLayout_4.addWidget(self.customer_name_lineEdit)
        self.customer_name_lineEdit.raise_()
        self.label_2.raise_()
        self.verticalLayout_12.addWidget(self.frame_4)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_7.setMinimumSize(QtCore.QSize(130, 0))
        self.label_7.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_7.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.payment_box = QtWidgets.QComboBox(parent=self.frame_8)
        self.payment_box.setMinimumSize(QtCore.QSize(200, 30))
        self.payment_box.setMaximumSize(QtCore.QSize(200, 30))
        self.payment_box.setObjectName("payment_box")
        self.horizontalLayout_8.addWidget(self.payment_box)
        self.payment_box.raise_()
        self.label_7.raise_()
        self.verticalLayout_12.addWidget(self.frame_8)
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(5)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        self.label_3.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_3.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.order_date_label = QtWidgets.QLabel(parent=self.frame_20)
        self.order_date_label.setMinimumSize(QtCore.QSize(0, 30))
        self.order_date_label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.order_date_label.setObjectName("order_date_label")
        self.horizontalLayout_16.addWidget(self.order_date_label)
        self.verticalLayout_12.addWidget(self.frame_20)
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(5)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_26)
        self.label_17.setMinimumSize(QtCore.QSize(130, 0))
        self.label_17.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_17.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.delivery_address_plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame_26)
        self.delivery_address_plainTextEdit.setMinimumSize(QtCore.QSize(200, 65))
        self.delivery_address_plainTextEdit.setMaximumSize(QtCore.QSize(200, 120))
        self.delivery_address_plainTextEdit.setObjectName("delivery_address_plainTextEdit")
        self.horizontalLayout_20.addWidget(self.delivery_address_plainTextEdit)
        self.verticalLayout_12.addWidget(self.frame_26)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        self.label_8.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_8.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.status_box = QtWidgets.QComboBox(parent=self.frame_12)
        self.status_box.setMinimumSize(QtCore.QSize(200, 30))
        self.status_box.setMaximumSize(QtCore.QSize(200, 30))
        self.status_box.setObjectName("status_box")
        self.horizontalLayout_10.addWidget(self.status_box)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_12.setMinimumSize(QtCore.QSize(130, 0))
        self.label_12.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_12.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.contact_info = QtWidgets.QLineEdit(parent=self.frame_15)
        self.contact_info.setMinimumSize(QtCore.QSize(200, 30))
        self.contact_info.setMaximumSize(QtCore.QSize(200, 30))
        self.contact_info.setObjectName("contact_info")
        self.horizontalLayout_11.addWidget(self.contact_info)
        self.contact_info.raise_()
        self.label_12.raise_()
        self.verticalLayout_12.addWidget(self.frame_15)
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_31)
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_10.setMinimumSize(QtCore.QSize(130, 0))
        self.label_10.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_10.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.note_input = QtWidgets.QPlainTextEdit(parent=self.frame_14)
        self.note_input.setMinimumSize(QtCore.QSize(200, 65))
        self.note_input.setMaximumSize(QtCore.QSize(200, 120))
        self.note_input.setObjectName("note_input")
        self.horizontalLayout_12.addWidget(self.note_input)
        self.verticalLayout_12.addWidget(self.frame_14)
        self.verticalLayout_11.addWidget(self.frame_31)
        self.horizontalLayout_9.addWidget(self.frame_29)
        self.frame_32 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_32.setStyleSheet("#frame_32{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_13.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_33 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_33.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(5)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_33)
        self.label_21.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        self.verticalLayout_13.addWidget(self.frame_33, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_34 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_34.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        self.label_4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_4.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.productName_comboBox = QtWidgets.QComboBox(parent=self.frame_5)
        self.productName_comboBox.setMinimumSize(QtCore.QSize(200, 30))
        self.productName_comboBox.setMaximumSize(QtCore.QSize(200, 30))
        self.productName_comboBox.setObjectName("productName_comboBox")
        self.horizontalLayout_5.addWidget(self.productName_comboBox)
        self.verticalLayout_14.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_5.setMinimumSize(QtCore.QSize(130, 0))
        self.label_5.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_5.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.cylindersize_box = QtWidgets.QComboBox(parent=self.frame_6)
        self.cylindersize_box.setMinimumSize(QtCore.QSize(200, 30))
        self.cylindersize_box.setMaximumSize(QtCore.QSize(200, 30))
        self.cylindersize_box.setObjectName("cylindersize_box")
        self.horizontalLayout_6.addWidget(self.cylindersize_box)
        self.verticalLayout_14.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_6.setMinimumSize(QtCore.QSize(130, 0))
        self.label_6.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_6.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.quantity_box = QtWidgets.QSpinBox(parent=self.frame_7)
        self.quantity_box.setMinimumSize(QtCore.QSize(200, 30))
        self.quantity_box.setMaximumSize(QtCore.QSize(200, 30))
        self.quantity_box.setObjectName("quantity_box")
        self.horizontalLayout_7.addWidget(self.quantity_box)
        self.verticalLayout_14.addWidget(self.frame_7)
        self.frame_35 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_35.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(5)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_35)
        self.label_13.setMinimumSize(QtCore.QSize(130, 0))
        self.label_13.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_13.setStyleSheet("font: 10pt \"Noto Sans\";\n"
"color: #808080;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_25.addWidget(self.label_13)
        self.product_quantity_available_label = QtWidgets.QLabel(parent=self.frame_35)
        self.product_quantity_available_label.setStyleSheet("font: 10pt \"Noto Sans\";\n"
"color: #808080;")
        self.product_quantity_available_label.setObjectName("product_quantity_available_label")
        self.horizontalLayout_25.addWidget(self.product_quantity_available_label)
        self.verticalLayout_14.addWidget(self.frame_35)
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_9.setMinimumSize(QtCore.QSize(130, 0))
        self.label_9.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_9.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.price_input = QtWidgets.QLineEdit(parent=self.frame_13)
        self.price_input.setMinimumSize(QtCore.QSize(200, 30))
        self.price_input.setMaximumSize(QtCore.QSize(200, 30))
        self.price_input.setObjectName("price_input")
        self.horizontalLayout_13.addWidget(self.price_input)
        self.verticalLayout_14.addWidget(self.frame_13)
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_34)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_16)
        self.label_11.setMinimumSize(QtCore.QSize(130, 0))
        self.label_11.setMaximumSize(QtCore.QSize(130, 16777215))
        self.label_11.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.amount_input = QtWidgets.QLineEdit(parent=self.frame_16)
        self.amount_input.setMinimumSize(QtCore.QSize(200, 30))
        self.amount_input.setMaximumSize(QtCore.QSize(200, 30))
        self.amount_input.setObjectName("amount_input")
        self.horizontalLayout_14.addWidget(self.amount_input)
        self.verticalLayout_14.addWidget(self.frame_16)
        self.verticalLayout_13.addWidget(self.frame_34)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_32)
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(5)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.addItem_btn = QtWidgets.QPushButton(parent=self.frame_11)
        self.addItem_btn.setMinimumSize(QtCore.QSize(125, 30))
        self.addItem_btn.setMaximumSize(QtCore.QSize(125, 30))
        self.addItem_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addItem_btn.setStyleSheet("background-color: #32CD32;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"border: none;\n"
"border-radius: 5px;")
        self.addItem_btn.setObjectName("addItem_btn")
        self.horizontalLayout_24.addWidget(self.addItem_btn)
        self.verticalLayout_13.addWidget(self.frame_11, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_9.addWidget(self.frame_32)
        self.verticalLayout_4.addWidget(self.frame_10, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_18)
        self.frame_17.setStyleSheet("background-color: transparent;")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_4.addWidget(self.frame_17, 0, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_5.addWidget(self.frame_18)
        self.orders_table_frame = QtWidgets.QFrame(parent=self.frame_2)
        self.orders_table_frame.setStyleSheet("#orders_table_frame{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}\n"
"*{\n"
"background-color: transparent;\n"
"}")
        self.orders_table_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.orders_table_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.orders_table_frame.setObjectName("orders_table_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.orders_table_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_37 = QtWidgets.QFrame(parent=self.orders_table_frame)
        self.frame_37.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_37)
        self.label_19.setStyleSheet("font: 87 16pt \"Noto Sans Black\";\n"
"color: #333333;")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_26.addWidget(self.label_19)
        self.verticalLayout_3.addWidget(self.frame_37)
        self.orders_tableWidget = QtWidgets.QTableWidget(parent=self.orders_table_frame)
        self.orders_tableWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.orders_tableWidget.setObjectName("orders_tableWidget")
        self.orders_tableWidget.setColumnCount(0)
        self.orders_tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.orders_tableWidget)
        self.verticalLayout_5.addWidget(self.orders_table_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_17.addWidget(self.frame_2)
        self.frame_19 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame_19.setStyleSheet("")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_6.addItem(spacerItem2)
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_23.setStyleSheet("#frame_23{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_25 = QtWidgets.QFrame(parent=self.frame_23)
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_25)
        self.label_15.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.verticalLayout_7.addWidget(self.frame_25, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.recent_orders_scrollArea = QtWidgets.QScrollArea(parent=self.frame_23)
        self.recent_orders_scrollArea.setStyleSheet("#recent_orders_scrollArea{\n"
"background-color: #EAEAEA;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F0F0F0;\n"
"                width: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.recent_orders_scrollArea.setWidgetResizable(True)
        self.recent_orders_scrollArea.setObjectName("recent_orders_scrollArea")
        self.recent_orders_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.recent_orders_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 350, 250))
        self.recent_orders_scrollAreaWidgetContents.setObjectName("recent_orders_scrollAreaWidgetContents")
        self.recent_orders_scrollArea.setWidget(self.recent_orders_scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.recent_orders_scrollArea)
        self.recent_orders_scrollArea.raise_()
        self.frame_25.raise_()
        self.verticalLayout_6.addWidget(self.frame_23)
        self.frame_27 = QtWidgets.QFrame(parent=self.frame_19)
        self.frame_27.setStyleSheet("#frame_27{\n"
"background-color: #fff;\n"
"border-radius: 5px;\n"
"}")
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_28 = QtWidgets.QFrame(parent=self.frame_27)
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_28)
        self.label_18.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.orders_quantity_label = QtWidgets.QLabel(parent=self.frame_28)
        self.orders_quantity_label.setStyleSheet("font: 63 12pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.orders_quantity_label.setObjectName("orders_quantity_label")
        self.horizontalLayout_3.addWidget(self.orders_quantity_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_10.addWidget(self.frame_28)
        self.ordered_items_scrollArea = QtWidgets.QScrollArea(parent=self.frame_27)
        self.ordered_items_scrollArea.setMinimumSize(QtCore.QSize(350, 320))
        self.ordered_items_scrollArea.setStyleSheet("#ordered_items_scrollArea{\n"
"background-color: #EAEAEA;\n"
"border: none;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar:hover{\n"
" cursor: pointer;\n"
"}\n"
"            QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #F0F0F0;\n"
"                width: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #90A4AE;\n"
"                border-radius: 7px;\n"
"                min-height: 30px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: #F0F0F0;\n"
"            }\n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 14px;\n"
"                margin: 0px 0px 0px 0px;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #555;\n"
"                border-radius: 7px;\n"
"                min-width: 30px;\n"
"            }\n"
"            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"                width: 0px;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"                background: #f0f0f0;\n"
"            }")
        self.ordered_items_scrollArea.setWidgetResizable(True)
        self.ordered_items_scrollArea.setObjectName("ordered_items_scrollArea")
        self.orders_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.orders_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 350, 320))
        self.orders_scrollAreaWidgetContents.setObjectName("orders_scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.orders_scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ordered_items_scrollArea.setWidget(self.orders_scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.ordered_items_scrollArea, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_27)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.finalize_order_pushButton = QtWidgets.QPushButton(parent=self.frame_9)
        self.finalize_order_pushButton.setMinimumSize(QtCore.QSize(125, 30))
        self.finalize_order_pushButton.setMaximumSize(QtCore.QSize(125, 30))
        self.finalize_order_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.finalize_order_pushButton.setStyleSheet("background-color: #32CD32;\n"
"font: 87 10pt \"Noto Sans Black\";\n"
"color: #fff;\n"
"border: none;\n"
"border-radius: 5px;")
        self.finalize_order_pushButton.setObjectName("finalize_order_pushButton")
        self.horizontalLayout_23.addWidget(self.finalize_order_pushButton)
        self.verticalLayout_10.addWidget(self.frame_9)
        self.verticalLayout_6.addWidget(self.frame_27)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.horizontalLayout_17.addWidget(self.frame_19)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Orders"))
        self.label_14.setText(_translate("Form", "Total Orders:"))
        self.label_16.setText(_translate("Form", "(Today)"))
        self.total_orders_label.setText(_translate("Form", "0"))
        self.view_order_pushButton.setText(_translate("Form", "View Orders"))
        self.order_history_pushButton.setText(_translate("Form", "Order History"))
        self.label_20.setText(_translate("Form", "Order Information:"))
        self.label_2.setText(_translate("Form", "Customer Name:"))
        self.label_7.setText(_translate("Form", "Payment Status:"))
        self.label_3.setText(_translate("Form", "Order Date:"))
        self.order_date_label.setText(_translate("Form", "TextLabel"))
        self.label_17.setText(_translate("Form", "Delivery Address:"))
        self.label_8.setText(_translate("Form", "Order Status:"))
        self.label_12.setText(_translate("Form", "Contact:"))
        self.label_10.setText(_translate("Form", "Remarks:"))
        self.label_21.setText(_translate("Form", "Product:"))
        self.label_4.setText(_translate("Form", "Product:"))
        self.label_5.setText(_translate("Form", "Cylinder Size:"))
        self.label_6.setText(_translate("Form", "Quantity:"))
        self.label_13.setText(_translate("Form", "Available:"))
        self.product_quantity_available_label.setText(_translate("Form", "0"))
        self.label_9.setText(_translate("Form", "Price:"))
        self.label_11.setText(_translate("Form", "Total Amount:"))
        self.addItem_btn.setText(_translate("Form", "Add Item"))
        self.label_19.setText(_translate("Form", "Orders Table"))
        self.label_15.setText(_translate("Form", "Recent Orders:"))
        self.label_18.setText(_translate("Form", "Ordered Items:"))
        self.orders_quantity_label.setText(_translate("Form", "0"))
        self.finalize_order_pushButton.setText(_translate("Form", "Confirm Order"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
