# Form implementation generated from reading ui file 'product_in_stock_info.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frame_info(object):
    def setupUi(self, frame_info):
        frame_info.setObjectName("frame_info")
        frame_info.resize(275, 41)
        self.horizontalLayout = QtWidgets.QHBoxLayout(frame_info)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.prod_name_label = QtWidgets.QLabel(parent=frame_info)
        self.prod_name_label.setStyleSheet("font: 63 10pt \"Noto Sans SemiBold\";\n"
"color: #333333;")
        self.prod_name_label.setObjectName("prod_name_label")
        self.horizontalLayout.addWidget(self.prod_name_label)
        self.quantity_label = QtWidgets.QLabel(parent=frame_info)
        self.quantity_label.setObjectName("quantity_label")
        self.horizontalLayout.addWidget(self.quantity_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(frame_info)
        QtCore.QMetaObject.connectSlotsByName(frame_info)

    def retranslateUi(self, frame_info):
        _translate = QtCore.QCoreApplication.translate
        frame_info.setWindowTitle(_translate("frame_info", "Frame"))
        self.prod_name_label.setText(_translate("frame_info", "Product Name:"))
        self.quantity_label.setText(_translate("frame_info", "Quantity"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frame_info = QtWidgets.QFrame()
    ui = Ui_frame_info()
    ui.setupUi(frame_info)
    frame_info.show()
    sys.exit(app.exec())
